### ISSUE TITLE
Add libresonic to a translation service

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#100]
After reading some comments and tried to translate some of the language files, i suggest that we add libresonic to a translations service !

Maybe Transifex  or so  ?

**Comment by jooola** [comment]
Its pretty much simple but i can't do this.
But @EugeneKay you're the one is ask to add this.

Here is the Howto :
 [http://docs.transifex.com/integrations/github/](url)

I guess you could host this, with the website instance ? ( you wanted to host it ? )

**Comment by jooola** [comment]
Is this the right time to try to implent transifex ?

**Comment by jooola** [comment]
Well, Transifex is a closed software and not free to use, so i searched some alternatives and i found [WebLate](https://weblate.org/en/).

I suggest we could use this ! Just need a server that could run this !

**Comment by jooola** [comment]
I just tested to run a Weblate instance on my server and it works well !
We could use it to properly build the l18n files for libresonic !

If this is a good idea I'll reinstall it for production !
What do you think ?

**Comment by jooola** [comment]
I took care of it and asked to weblate if they can host a translation service for use. They answered YES !
And so we have a translations service up here : 
https://hosted.weblate.org/projects/libresonic/develop/

Hope this is good for everyone ?
@Libresonic/libra 

Is this a good idea if weblate push new translations to libresonic repo ?

**Comment by jooola** [comment]
@EugeneKay I need your help to integrate this to the libresonic repo.

If we want to notify Weblate every push in the repo follow [this guide](https://docs.weblate.org/en/latest/admin/continuous.html#github-setup)
I think this is the bare minimum we should do.

And if we want that weblate push translation update to the repo you need to follow [this guide](https://docs.weblate.org/en/latest/admin/continuous.html#hosted-push)
I think we shoudl enable this too.

**Comment by jooola** [comment]
What does Libresonic users think of this issue ?
@muff1nman @biconou @EugeneKay @fxthomas @alexfornuto

**Comment by EugeneKay** [comment]
@jooola Pinging every user is not a good way to get attention for this issue.

I personally do not really care about a translation service - there are much bigger fish to fry IMO. I think it is great that you are looking up services, but I have no idea how this will integrate with the rest of the project and I do not really have the time/effort to spare to deal with it due to real life.

Patience is a virtue.

**Comment by biconou** [comment]
Personality, I have no idea of the necessity of a translation. As a Java developer I prefer to concentrate my efforts on creating features.  When I create a new label I just create it in English  as a bare minimum. But making Libresonic more attractive through it's user interface is important too and @jooola is an enthousiastic contributor for that. For the moment I have no opinion about a translation service but the topic seams being studied.
