### ISSUE TITLE
Add keyboard shortcuts ?

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#101]
I'm up to add the keyboard shortcuts features to libresonic !
And easy to do ! commits are in the subsonic-svn repo !

Here is some more :
[https://github.com/Libresonic/subsonic-svn/commit/1213f8fc2a10655c0909eec631550131a10479dd](url)

[https://github.com/Libresonic/subsonic-svn/commit/12a0e1626461d98174d141e6920ead4e16268107](url)

Need to search in the subsonic-svn some other commits ( fixes and others adds for this features ).

I'll probably do it, but only when i have some time.

**Comment by EugeneKay** [comment]
Personally I despise keyboard shortcuts in browser applications, but I understand that these are helpful. I am open to including this feature, however:

- It must be optional and off by default
- The commits referenced can not be cherry-picked directly, as they include unrelated changes
- Perhaps shortcuts should be user-customizable?

**Comment by fxthomas** [comment]
Aren't the current keyboard shortcuts on by default? I, for one, have been using them all the time since Sindre first released 6.0-beta1.

I'm actually missing the "star" and "toggle queue" shortcuts present in 6.0-beta2, and I'd love to have them back in Libresonic!

**Comment by afxgit** [comment]
Libresonic 6.0.1

First recommended release
Based upon Subsonic 5.3(stable)
v6.0 was tagged prematurely

**Comment by fxthomas** [comment]
@afxgit Ha, thanks, I was out of country for a month and did not notice the rebase. Then let's just say that I'm also heavily interested in re-adding this feature to Libresonic! :smile: 

Call it scratching my own itch, but I will have some time to prepare a PR this weekend, is that okay with you or is somebody else already working on this?

Re: reusing code, anything wrong with just (for now) extracting the existing beta1 code and adding an optional _Enable Keyboard Shortcuts_ switch in under _Settings_ > _Personal_?

**Comment by jooola** [comment]
As i sayd look at the different commits on subsonic-svn repo and write the code.
i didn't work on this features right now so you can peacefully start to work on it !

**Comment by fxthomas** [comment]
@jooola Excellent, that's what I wanted to know :)

**Comment by jooola** [comment]
Take note of the  EugeneKay comment !
- The commits referenced can not be cherry-picked directly, as they include unrelated changes !

**Comment by fxthomas** [comment]
@jooola That's what I meant by "extracting" and adding a user setting, don't worry! However, it seems to me that @EugeneKay's last point should have its own issue/PR once the base functionality works.
