### ISSUE TITLE
No items in main window pane

### ISSUE THREAD

**Issue by nickermire** [Libresonic/libresonic#111]
I downloaded a jenkins build from 6/21/16. But am not able to see any items in the main window pane. Instead all imported songs are showing up in a long list in the playlists pane.

**Comment by philcryer** [comment]
I had this issue recently with the newer versions of Subsonic, for me it was a matter of the user not having permissions to the default Music directory. Log in as admin, hit `Settings -> Users -> From the dropdown next to 'Select User', choose your user -> check the box by 'Allow access to these media folders' -> Logout` then login as that user and see if they can see the files in Music.

**Comment by nickermire** [comment]
My issue was with how my music was laid out within the file system. I didn't realize that the sonics use directory structure to parse artist, album and songs. Thank you all for your time,
Nick

On Thu, Jun 23, 2016 at 12:34 PM, Phil Cryer <notifications@github.com> wrote:
I had this issue recently with the newer versions of Subsonic, for me it was a matter of the user not having permissions to the default Music directory. Log in as admin, hit Settings -> Users -> From the dropdown next to 'Select User', choose your user -> check the box by 'Allow access to these media folders' -> Logout then login as that user and see if they can see the files in Music.
