### ISSUE TITLE
Strange error while synchronising 

### ISSUE THREAD

**Issue by djdmd** [Libresonic/libresonic#112]
Hello
I have libresonic suynchonisng starrd songs with dsub on my android and i have this strange message in logs

> WARN RESTFilter - Error in REST API: PreparedStatementCallback; SQL [insert into play_queue_file(play_queue_id, media_file_id) val
> ues (?, ?)]; Integrity constraint violation - no parent SYS_FK_218 table: MEDIA_FILE in statement [insert into play_queue_file(play_queue_id, media_file_id)
>  values (?, ?)]; nested exception is java.sql.SQLException: Integrity constraint violation - no parent SYS_FK_218 table: MEDIA_FILE in statement [insert int
> o play_queue_file(play_queue_id, media_file_id) values (?, ?)]

**Comment by bajansen** [comment]
Do you know at what point libresonic generates these errors? What action in Dsub will trigger this warning?

**Comment by djdmd** [comment]
It happens when i try syncing with latest version of dsub , i'v tried with another one (5.1.8) and its ok , i think i'll open an issue on dsub github.

**Comment by EugeneKay** [comment]
I'm unable to replicate this. Can you provide `adb logcat` output from DSub ?

**Comment by djdmd** [comment]
Hi 
Where can i find it ?

**Comment by EugeneKay** [comment]
Closing this Issue as it is old. Please reopen after testing against 6.1(stable) and include adb logcat debug information.
