### ISSUE TITLE
Arbitrary frontend reloads

### ISSUE THREAD

**Issue by vestingz** [Libresonic/libresonic#113]
The home view (and possibly all other views, too) automatically refresh every ~30secs with no apparent reason. Especially in random view this has the annoying effect of an ever changing order of albums.

**Comment by csobsidian** [comment]
I believe that was default behavior of Subsonic.

**Comment by vestingz** [comment]
Any way to disable this? It's quite annoying, especially when browsing the random section.

**Comment by EugeneKay** [comment]
This is controlled/caused by this line: https://github.com/Libresonic/libresonic/blob/develop/libresonic-main/src/main/webapp/WEB-INF/jsp/home.jsp#L10

I would welcome a PR to add a Setting for this value(or "0" to disable auto-refresh).

**Comment by fxthomas** [comment]
Ha, this one actually annoyed me a few times. Since I already did something very similar in another PR, I added #115 to fix that. Feel free to test/comment.

**Comment by vestingz** [comment]
Kool :) Will test as soon as i find time. Thank you!

**Comment by fxthomas** [comment]
Note that it includes a change in the database schema, so it's probably not a good idea to test it on your production database! (But nobody does that, right? :smiling_imp: )

**Comment by vestingz** [comment]
Ugh, good to know :)

**Comment by zifnab06** [comment]
Fixed by #115, going to close this now.
