### ISSUE TITLE
Demo Site

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#116]
Set up a Demo site for evaluation, possibly using Docker. Integrate with Jenkins for live testing of the develop branch?

**Comment by peterpacz1** [comment]
+1

**Comment by drewbagel423** [comment]
Agreed. Or at the very least, a screenshot of what the program looks like?

**Comment by bobberb** [comment]
Would also appreciate a screenshot from anyone involved.

**Comment by muff1nman** [comment]
@bobberb @drewbagel423  Screenshot added in case youre still interested.

**Comment by EugeneKay** [comment]
https://libresonic.org/libresonic

Username: demo
Password: libresonic

I have not loaded any media into this instance, and the path is liable to change. Once this has become stable I will add relevent links into the documentation.
