### ISSUE TITLE
Documentation: Reverse-Proxying

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#119]
Add documentation for adding a reverse proxy server(Apache or Nginx) in front of Libresonic under a Tomcat server.

**Comment by fxthomas** [comment]
I've currently been using this for Nginx so that I can access Libresonic at `https://example.com/libresonic` :

```nginx
# Always redirect to the HTTPS version
server {
    listen      80;
    server_name example.com;
    return      301 https://$server_name$request_uri;
}

server {

    # SSL setup
    listen       443 default ssl;
    server_name  example.com;
    ssl_certificate      cert.pem;
    ssl_certificate_key  key.pem;

    # Libresonic Proxy
    location /libresonic {
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header Host              $http_host;
      proxy_max_temp_file_size           0;
      proxy_pass                         http://127.0.0.1:4040;
      proxy_redirect                     http:// https://;
    }
}
```

Along with the following options in the startup script :

```bash
libresonic.host=127.0.0.1
libresonic.port=4040
libresonic.httpsPort=0
libresonic.contextPath=/subsonic
```

**Comment by jooola** [comment]
Here is a configuration to use libresonic behind a reverse proxy like HAProxy : 


frontend http
	bind $server_public_ip$:80

	acl url_libresonic path_beg -i /libresonic
	use_backend libresonic-backend if url_libresonic

# Change default backend to libresonic backend if you don't have a web backend
	default_backend web-backend

backend libresonic-backend
	server subsonic 192.168.122.10:8443 check


# With ssl implementation

frontend https
	bind $server_public_ip$:443 ssl crt /etc/haproxy/ssl/$server_ssl_keys$.pem

	acl url_libresonic path_beg -i /libresonic
	use_backend libresonic-backend if url_libresonic

# Change default backend to libresonic backend if you don't have a web backend
	default_backend web-backend

backend libresonic-backend
	redirect scheme https if !{ ssl_fc }
	server subsonic 192.168.122.10:8443 check ssl verfiy none




Obsiously the libresonic context_path need to be changed.

**Comment by nobswift** [comment]
ok, after struggeling for a week or so i found out how it works with nginx

   location ^~ /libresonic {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8080/libresonic;
        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
        add_header X-Content-Type-Options "nosniff";
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
    }

this configuration works for me when using libresonic with a standard tomcat configuration.

i just closed port 8080 of tomcat afterwards by adding the "address" parts to the connectors.

  <Connector port="8080" protocol="HTTP/1.1"
               connectionTimeout="20000"
               address="127.0.0.1"
               redirectPort="8443" />

**Comment by m1dnight** [comment]
```
<VirtualHost *:80>
        ServerName subsonic.call-cc.be
        ErrorDocument 404 /404.html
        DocumentRoot /var/www
        ProxyPass         / http://localhost:4040/
        ProxyPassReverse  / http://localhost:4040/
        Header always unset X-Frame-Options

</VirtualHost>
```

This is my configuration for Apache2. Notice that I have unset a header for the I-Frames, I think this is less secure than original, but the only way to make it work as far as I have found. Glad to hear some feedback on this.

**Comment by djdmd** [comment]
`server {
        listen 80;
        server_name subdomain.mydomain.net; #name server
        location / {
                proxy_pass http://127.0.0.1:4040;
                proxy_redirect off;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
}
`

**Comment by muff1nman** [comment]
The documentation for this has now been added. Please create a new PR for any further additions.

**Comment by jooola** [comment]
Wowowow wait ! The haproxy config is wrong, you changed it and it won't work.

**Comment by fxthomas** [comment]
@joola Care to elaborate? I have admittedly never used HAProxy. If my memory serves right I copied the HTTPS settings only, changing the IP address to be consistent with how other web servers are setup.

**Comment by jooola** [comment]
Yup sorry working on something else i was a bit fast ...

This won't work :

`frontend https
bind $server_public_ip$:443 ssl crt /etc/haproxy/ssl/$server_ssl_keys$.pem

# Let Libresonic handle all requests under /libresonic
acl url_libresonic path_beg -i /libresonic
use_backend libresonic-backend if url_libresonic

# Change default backend to libresonic backend if you don't have a web backend
default_backend web-backend

backend libresonic-backend
server libresonic 127.0.0.1:4040 check`

Because of 
`backend libresonic-backend
server libresonic 127.0.0.1:4040 check`

If it is HTTPS it need to be like this : 
`backend libresonic-backend
    redirect scheme https if !{ ssl_fc }
    server libresonic 192.168.122.10:8443 check ssl verfiy none`

**Comment by jooola** [comment]
And one more thing, sorry.
SSL must be activated on libresonic in the configuration file !
`LIBRESONIC_ARGS="--port=0 --https-port=8443`

**Comment by muff1nman** [comment]
SSL is no longer supported by libresonic.

**Comment by jooola** [comment]
Okay , well why ? let the reverse proxy handle that ?
So just ignore my last comment !

**Comment by muff1nman** [comment]
Yes if I remember the discussion we had at some point the idea was that if you want ssl, it should be done in the proxy and that libresonic would not offer any support for https directly. To be honest I did not test the HAProxy configs, but the nginx settings are good.

**Comment by jooola** [comment]
Ok i'll try it in the next days ! But for now i don't think this work !

**Comment by muff1nman** [comment]
If the HA proxy settings are bugged, please open a new issue specific to haproxy. This issue was for adding a proxy document in general.

**Comment by jooola** [comment]
Damn i wanted to test the haproxy config , but i can't get a libresonic instance running ...

```
INFOS: Déploiement de l'archive /var/lib/tomcat8/webapps/libresonic.war de l'application web
[2017-02-01 03:48:11,827] ERROR org.springframework.web.context.ContextLoader - Context initialization failed
java.lang.UnsupportedClassVersionError: org/libresonic/player/spring/AdditionalPropertySourceConfigurer : Unsupported major.minor version 52.0 (unable to load class org.libresonic.player.spring.AdditionalPropertySourceConfigurer)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2476)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:853)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1263)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1146)
	at org.springframework.util.ClassUtils.forName(ClassUtils.java:250)
	at org.springframework.web.context.ContextLoader.loadInitializerClass(ContextLoader.java:519)
	at org.springframework.web.context.ContextLoader.determineContextInitializerClasses(ContextLoader.java:509)
	at org.springframework.web.context.ContextLoader.customizeContext(ContextLoader.java:466)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4832)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:919)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1703)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
févr. 01, 2017 3:48:11 AM org.apache.catalina.core.StandardContext startInternal
GRAVE: Error listenerStart
```

If anyone could help me ... I suck with Java and Tomcat

**Comment by muff1nman** [comment]
Wrong Java version.

**Comment by jooola** [comment]
Could you be more specific ?

I installed open-jdk-8-jre, Set as default java 8 changed $JAVA_HOME in /etc/default/tomcat8 to JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

But still don't work,

**Comment by muff1nman** [comment]
There's not really much more I can say. `java.lang.UnsupportedClassVersionError` means that tomcat is not running with Java 8. For whatever reason your change in `/etc/default/tomcat8` is being ignored. I would suggest checking your tomcat logs. It could even be you're using tomcat 7 or something.

**Comment by muff1nman** [comment]
And if you still need more help, open a new issue. This one is specific to proxy doc
