### ISSUE TITLE
Would it be possible to integrate this patch ?

### ISSUE THREAD

**Issue by silviuvulcan** [Libresonic/libresonic#120]
I'm running the 5.3 version and I'm hitting exactly this issue. I use haproxy with ssl on the frontend and subsonic in http mode on the backend - even configuring the external address doesn't help the web interface to work.

This patch should fix it, can it be added?
https://sourceforge.net/p/subsonic/patches/23/

**Comment by jooola** [comment]
They are actually a work around before the patch is integrated : The ticket talking about that is the #119

**Comment by muff1nman** [comment]
Closing as @jooola points out #119 for reverse proxy discussion. In addition, the booter side is receiving minimal work as it will be replaced
