### ISSUE TITLE
Ignore IntellliJ project description in source control

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#121]
This issue is for discussion. 

I usually think it is a good Idea to exclude any IDE dependant project description files from source control. 
Indeed, using Maven, the POM must be sufficient. Thus you can "import" the project in any IDE. 

(Personnaly I noticed diffences in these files between IntelliJ 14 and 16).

I suggest to remove .iml and .idea from git repo. 
Any opinion ? 

Note that the libresonic.iml actually commited is not coherent with the pom.xml in java langage level (pom -> 1.8, iml -> 1.6).

**Comment by muff1nman** [comment]
Yes, these need to be removed.
