### ISSUE TITLE
Wrong version of servlet and jsp api

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#122]
Regarding the installation documentation, libresonic targets java8 and Tomcat8 (that's good).

But, in the libresonic-main pom.xml, the versions are wrong for servlet and jsp api.

```
    <dependency>
        <groupId>javax.servlet</groupId>
        <artifactId>servlet-api</artifactId>
        <version>2.4</version>
        <scope>provided</scope>
    </dependency>

    <dependency>
        <groupId>javax.servlet</groupId>
        <artifactId>jsp-api</artifactId>
        <version>2.0</version>
        <scope>provided</scope>
    </dependency>
```

Indeed Tomcat 8 uses these versions of the apis : 
Servlet 3.1
JSP 2.3

see : http://tomcat.apache.org/whichversion.html

**Comment by biconou** [comment]
Ok, I am currently working on that issue. I also manage to add the support of jetty as  lightweight server for development purpose.

**Comment by fxthomas** [comment]
Jetty support will be really useful, deploying to Tomcat during development is a pain! Does Libresonic have a developer "getting started" page I'm not aware of? If so it should be there.

**Comment by biconou** [comment]
Good news. Jetty plugin support is now available on a PR I submitted. 
I planned to work on a guide to setup a development environment. 
But at the moment I am working on a port on Jetty in production mode as a standalone jar. There are some tricky stuffs.

**Comment by biconou** [comment]
I just added support of standalone application with Jetty in my PR.
Enjoy.

**Comment by muff1nman** [comment]
We are at 3.1 now, so this can be closed:
```
        <dependency>
            <groupId>javax.servlet</groupId>
            <artifactId>javax.servlet-api</artifactId>
            <version>3.1.0</version>
            <scope>provided</scope>
        </dependency>

```
