### ISSUE TITLE
https configuration option not working

### ISSUE THREAD

**Issue by gsantner** [Libresonic/libresonic#125]
Hi there,
I just installed LibreSonic from v6.1beta1 from the built debian package. I tried it multiple times, but the I could not deploy the war file to my tomcat..hmm. 

I tried multiple variations, but always if I add the `--https-port=` option to `/etc/default/libresonic` Libresonic won't start anymore. So https is not usable.

I tried multiple variations:
```
LIBRESONIC_ARGS="--max-memory=1024 --host=0.0.0.0 --https-port=9040 --context-path=/libresonic"

LIBRESONIC_ARGS="--max-memory=1024 --host=0.0.0.0 --http-port=9041 --https-port=9040 --context-path=/libresonic"
```
I am happy about any hint.

**Comment by nobswift** [comment]
I would recommend to leave most of the settings standard and use a webserver/proxy instead like apache or nginx. I personally prefer nginx. Config SSL in nginx settings like this:
'''
server {
    listen      443 ssl http2;
    listen [::]:443 ssl http2;
    ssl on;
    server_name subdomain.domain.tld;

    ssl_certificate /etc/letsencrypt/live/xxx/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xxx/privkey.pem;
    ssl_dhparam /etc/letsencrypt/live/xxx/dhparam.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/xxx/fullchain.pem;
    ssl_ecdh_curve secp384r1;

    server_tokens off;
    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;
    ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
    ssl_prefer_server_ciphers on;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
    ssl_session_tickets off;

    ssl_stapling on;
    ssl_stapling_verify on;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # Add headers to serve security related headers
    add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload;" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
'''

redirect a subfolder to standard tomcat:

'''
    location ^~ /libresonic {
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8080/libresonic;
    }

'''

this works fine for me.

**Comment by gsantner** [comment]
I'am using Apache as reverse proxy, but still, the builtin https option does not work :)

**Comment by EugeneKay** [comment]
The built-in HTTPS is not recommended and will be removed in a future version. You should use a reverse-proxy(eg, Apache or Nginx) in front of Libresonic for public deployments.

**Comment by gsantner** [comment]
@EugeneKay 
Then the project should provide a good&working https conf file for both, apache & nginx ;)

**Comment by EugeneKay** [comment]
@gsantner See #119 ;-)

**Comment by youkoso** [comment]
Same here. I've setup a simple reverse-proxy with nginx, but can't do anything because of `The page at 'https://xxxxxx.net/index.view' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxx.net/musicFolderSettings.view'. This request has been blocked; the content must be served over HTTPS.`
