### ISSUE TITLE
Standardize import ordering

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#127]
As we get more contributions, it will be nice to have a standard for import order. This will also keep changesets readable and minimize merge conflicts. Thoughts?

**Comment by biconou** [comment]
That's a great question.
Personnaly I use to let IntelliJ organize then automatically. Do you think it's a bad practice ?

**Comment by bfkelsey** [comment]
Best to be consistent so you aren't always clashing. Here is what I had to use: 
![screenshot from 2016-12-19 21-21-40](https://cloud.githubusercontent.com/assets/131458/21339118/665b195e-c631-11e6-8122-c675fd9e2376.png)
