### ISSUE TITLE
Repo Activity

### ISSUE THREAD

**Issue by daneren2005** [Libresonic/libresonic#128]
There has been no repo activity in quite a while.  Pull Requests seem to be ignored.  I honestly didn't even start contributing to this because I had a feeling this would happen.  If you don't have time to actively maintain this project, do you want to add a few people as admins so the work can go on?  For the first time we have a chance to have a decent community fork of Subsonic with real user contribution, and I hate to see it just die like this after only a few months of activity.

**Comment by biconou** [comment]
Hi,
I partly agree with you. Perhaps there are too few admins.
But I don't think that not contributing is a good strategy.
Github hopefully helps any contribution. The more we will create pull requests, the more the project will remain alive. 
I am working on a usefull feature. A new, more efficient jukebox player. And I got many ideas ahead. Spare time is missing but I am convinced that Libresonic will grow up.
Please, contribute :-)

**Comment by biconou** [comment]
Anyway, where is  @EugeneKay our father ?

**Comment by EugeneKay** [comment]
Buried at work ;-)

I have a backlog of items to review here. I have been testing out patches on my local dev environment, but its not in a good state right now. I think I'm going to back them all out and just release a stable 6.1 essentially from where it sits, then look at these refactors.

**Comment by daneren2005** [comment]
That is fine.  Anyone is going to have times where they just can't get stuff done.  That is why I suggest adding some additional contributors.  It both takes away the burden from yourself and removes the single point of failure (ie: You get busy for months at a time).

**Comment by EugeneKay** [comment]
Totally. @zifnab06 is on the list already, and I'd be happy to add more people to work on the develop branch. I am mostly interested in the stable branch for my personal needs. I welcome suggestions on an application/qualification process.

**Comment by muff1nman** [comment]
I wouldn't mind helping review pull requests and getting them merged if we need help there.

**Comment by EugeneKay** [comment]
I have added @muff1nman to manage the "develop" branch.
