### ISSUE TITLE
Cast icon is not appearing with Chromium 54

### ISSUE THREAD

**Issue by Tapchicoma** [Libresonic/libresonic#130]
Chrome/Chromium 54 introduced built-in media-router (enabled by default) that replaces chrome cast extension.
When this media-router is enabled - cast icon is not appearing near player.
When I disable it through flags - everything becomes ok.

Documentation for media-router: https://www.chromium.org/developers/design-documents/media-router

**Comment by EugeneKay** [comment]
Well this is unfortunate. Do you know if other browsers(eg, Firefox, Opera, IE) will be implementing the same media-router API? If they are not then it may not be worth the effort to port over from Chromecast. I personally only use mobile devices(phone) to Cast, so I did not notice this.

**Comment by Tapchicoma** [comment]
Initially Chromecast streaming was only available at Chrome/Chromium browser and no other browsers tries to implement it. I don't think that it will be changed in the future. Though sometimes it is useful to have ability to stream music from browser.

**Comment by j0nnymoe** [comment]
will the removal of this feature causes any issues with clients casting audio to chromecasts?
For example, I use dsub client to cast from libresonic to my chromecast audio.

**Comment by fxthomas** [comment]
AFAIK clients use their own implementation of casting so they should be fine, right?

**Comment by Tapchicoma** [comment]
@fxthomas you are right, but sometimes I prefer to use browser version to stream music to my speakers.

I will try to update current cast implementation to v3 and see if it helps.

**Comment by jooola** [comment]
This can be closed right ? PR has been merged !
