### ISSUE TITLE
FLAC files appear as MP3 in play queue

### ISSUE THREAD

**Issue by fxthomas** [Libresonic/libresonic#131]
A small cosmetic thing is bugging me : FLAC files appear as MP3 in the play queue :

![screenshot from 2016-10-28 22-25-00](https://cloud.githubusercontent.com/assets/613594/19821248/a5ce3942-9d5d-11e6-911f-7b4af3974b0f.png)

Apparently `PlayQueueService.formatFormat` tries to get the format from the transcoder (mine always transcodes to MP3), which is somewhat misleading as bitrate column next to it still reports the bitrate of the original file.

Shouldn't Libresonic show the actual file format there to stay consistent?

**Comment by DavidARussell** [comment]
This seems straightforward to fix, but in what "direction" should it be fixed (i.e. should the file format change to show the original format of the file, or should the bitrate change to show the post-transcoding bitrate?)

**Comment by DavidARussell** [comment]
The PR I just opened uses the first approach (make the file format column match the original file) which is what the reporter originally requested.

**Comment by fxthomas** [comment]
I prefer showing the original format, so thanks for the PR!
