### ISSUE TITLE
Add more filters to the shuffle feature

### ISSUE THREAD

**Issue by fxthomas** [Libresonic/libresonic#134]
The shuffle feature could use some love. I'd like to propose adding the following filters until it can be properly redesigned :

![screenshot from 2016-10-29 21-16-21](https://cloud.githubusercontent.com/assets/613594/19832174/fc660d24-9e1c-11e6-81db-55f1211a97ac.png)

Note the "Add to playlist" button, which adds to the current playlist if one exists instead of replacing it.

Existing version for comparison :

![screenshot from 2016-10-29 21-10-57](https://cloud.githubusercontent.com/assets/613594/19832138/3d14e0ee-9e1c-11e6-89a0-8a6ab68899bd.png)

This shouldn't break any existing functionality and is buried under the "More" menu, so I believe the change should quite safe and could be included in 6.2. What do you think?

**Comment by fxthomas** [comment]
After looking at this a little, the `randomSongs` feature uses the Lucene search index, which means that it has no easy access to star ratings and others.

I question the use of Lucene for this : it is a text-search engine, probably unsuited for searching something that isn't text.

Early experiments with `db.view` show that `select top 20 * from media_file order by rand()` is much faster than the current Lucene-based implementation while being easier to work with : in average over 10 samples, 75ms vs 420ms for the approx. 10,000 files in my collection.

If someone has a larger collection, could you post timings for the same query so that I know if this behavior scales well?

**Comment by neilweber** [comment]
The REST API also uses Lucene to get random albums which seems pretty odd given some of the other API album functions like 'frequent' is implemented via a direct query against the database.  I looked into this primarily because I use the random album REST API a lot and have noticed it's not very random.  With 800+ albums in my collection, I seem to see more repeats than I would expect.

**Comment by fxthomas** [comment]
Re: feeling of randomness, there's probably not much more we can do about it, the code is literally "load all results and pick a random index 20 times". Also, the "it's not very random" feeling is known to be [highly subjective](https://en.wikipedia.org/wiki/Clustering_illusion) anyway.

But that's why I think the filters I proposed would be really a great addition : on a large library like mine, some albums get forgotten by the random, and I sometimes like to play titles that haven't been listened to for a while.

**Comment by fxthomas** [comment]
I added a PR I quickly put together over the last few days. I'd love to see comments and suggestions on it.

The way I see it, this could be the starting point for implementing smart playlists on Libresonic, which is a feature I've been wishing for for a long time.

**Comment by fxthomas** [comment]
Closing since the PR is merged.
