### ISSUE TITLE
rename branch "stable" to "master"

### ISSUE THREAD

**Issue by chpio** [Libresonic/libresonic#140]
While the *master* branch is search-able through search engines like google, [other branches are not](http://stackoverflow.com/a/15987482). Renaming the main branch to *master* would increase the presence of this project in google.

PS: the configs of the guidelines for contributing are broken, it's added to an issue when creating a new one.

**Comment by EugeneKay** [comment]
No.

I dislike the overuse of the default "master" branch name in the git world, as it does not clearly have a purpose. I was not aware of the non-indexing of other branches, but I consider that to be a Feature - my preference would be that any and all documentation end up on the libresonic.org website (which I admit needs to be created and populated), not on a third-party code hosting service. Indexing the content here would negatively impact future search results by outranking them.
