### ISSUE TITLE
New Shuffle behaviour does not work as expected

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#141]
The new Shuffle behaviour(from #132) keeps the first track where it is, and shuffles the remainder of the list. This works great when you add a lot of songs, play the first, and then click Shuffle. It does not work as expected if you Shuffle the list later - eg, after the Player has moved onto the second track.

The expected behaviour is for the currently-playing track to "float" to the top of the list, and all of the OTHER tracks to be shuffled.

**Comment by fxthomas** [comment]
Whoops. I guess this serves as a humbling reminder that I should have tested this more, but damn those users for trying out unexpected things :)

I'll send a fix soon!

**Comment by fxthomas** [comment]
Fix sent as #144. I tested the web and REST interfaces, but I'd like another pair of eyeballs if possible.

**Comment by EugeneKay** [comment]
Tests good, and PR has been merged. Thanks!
