### ISSUE TITLE
Archlinux integration

### ISSUE THREAD

**Issue by Superpiffer** [Libresonic/libresonic#146]
I'm trying to create an AUR package of libresonic on Archlinux for beta versions. I've created [this](https://aur.archlinux.org/packages/libresonic/) package for the stable version and it works. 
The problem is that right now I use the booter from the original subsonic package, with the new beta it's not working anymore because of the different working paths. 
Is it possible to have the file libresonic-booter-jar-with-dependencies.jar builded with the .war file in the next releases? Of course I can build myself but may be a problem with the PKGBUILD.

**Comment by stevenroose** [comment]
I'm on Arch too (even though I will use Debian to install LibreSonic), so I can help test if you need anything.

**Comment by fxthomas** [comment]
Seconding this. It'd be great if this next release came with the same standalone archive (containing both the WAR and the booter JAR) as the original, we'd be able to reuse the Subsonic PKGBUILD with minimal changes.

**Comment by zifnab06** [comment]
I made a change to the jenkins job we've been using for testing/releasing. Should be included from now on for builds after this one: 
https://jenkins.undocumented.software/job/libresonic/232/

**Comment by Superpiffer** [comment]
I edited my PKGBUILD with the new .jar file and the latest beta release and it works. It would be better, as @fxthomas said, with a standalone package in order to have also the libresonic.sh but it's fine for now.
Thanks.

**Comment by zifnab06** [comment]
No problem. 

I think there's been talk about moving to springboot, which I think would drop the libresonic-booter requirement entirely. May hold off on making any other changes to it for now.

**Comment by Superpiffer** [comment]
I've updated the AUR package with the new stable version using the original subsonic package as base and the booter from jenkins, if anyone wants to try. Works for me.
