### ISSUE TITLE
maven package broken since latest PR integration

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#147]
I just ran a mvn:install on the entire project (branch develop) and I got the following error.

> [INFO] --- maven-dependency-plugin:2.10:analyze-only (analyze) @ libresonic-main ---
> [WARNING] Used undeclared dependencies found:
> [WARNING]    org.springframework.security:spring-security-core:jar:3.2.9.RELEASE:compile
> [WARNING] Unused declared dependencies found:
> [WARNING]    org.springframework.security:spring-security-config:jar:3.2.9.RELEASE:compile
> [WARNING]    org.springframework.security:spring-security-ldap:jar:3.2.9.RELEASE:compile
> [INFO] ------------------------------------------------------------------------
> [INFO] Reactor Summary:
> [INFO] 
> [INFO] Libresonic ........................................ SUCCESS [4.690s]
> [INFO] Libresonic REST API ............................... SUCCESS [14.797s]
> [INFO] Sonos API ......................................... SUCCESS [17.591s]
> [INFO] Libresonic Main ................................... FAILURE [1:06.617s]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------

**Comment by fxthomas** [comment]
Can we finish the Travis setup so that we have a working CI? A Libresonic admin just has to enable it and we're good to go.

**Comment by muff1nman** [comment]
@EugeneKay can you help?

@biconou I'll I see are warnings. Do you have the full output?

**Comment by fxthomas** [comment]
@muff1nman There you go : https://gist.github.com/fxthomas/2c211e1a0bacec4525ec1f215b13e16e

**Comment by EugeneKay** [comment]
@muff1nman I thought that I had accepted the Travis CI request, but I don't see it listed under Integrations now. What needs to be done?

**Comment by zifnab06** [comment]
You have to sign in at travis-ci.org and enable it for the project. Just did it.

**Comment by zifnab06** [comment]
Travis works. I'll have a patch up shortly to fix the failed build (#143 is to blame)

**Comment by zifnab06** [comment]
https://travis-ci.org/Libresonic/libresonic/jobs/179160255. Travis should check all future PRs to avoid this.
