### ISSUE TITLE
Missing "Remember me" checkbox after Spring 3 migration

### ISSUE THREAD

**Issue by fxthomas** [Libresonic/libresonic#151]
The "Remember me" checkbox went missing after the migration to Spring 3. I use this, is there a way to get it back before the release?

Before → after :

![screenshot from 2016-11-27 19-00-20](https://cloud.githubusercontent.com/assets/613594/20650792/6ad72196-b4d7-11e6-98ab-7ddf960c6e33.png) ![screenshot from 2016-11-27 19-03-06](https://cloud.githubusercontent.com/assets/613594/20650794/6d13ad3a-b4d7-11e6-811e-42f97935ab8e.png)

**Comment by muff1nman** [comment]
Yep, this one is my fault, I'll work on this.

**Comment by jooola** [comment]
I think all the remember me features are not safe ! so maybe we could add a way to enable/disable this feature too ?

**Comment by fxthomas** [comment]
@jooola Indeed they aren't. They also use MD5, so you definitely should not trust sensitive passwords to them.

I personally use them knowing this, and they are not dangerous if you don't check the checkbox, but I agree that not everybody will notice.

**Comment by muff1nman** [comment]
@jooola This issue was mainly for fixing what previously worked before. As @fxthomas mentioned, you don't have to use the feature by not clicking the check box, but if you want to see a way to completely disable remember me, please open another issue and we can continue discussion there.
