### ISSUE TITLE
PasswordSettingsController no more used ?

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#158]
org.libresonic.player.controller.PasswordSettingsController seams to be no more used (part of UserSettingsController).
What do you think. 
If yes, I'll remove it while migrating to Spring 4.

**Comment by fxthomas** [comment]
It doesn't seem to be used by any page or link, so it's probably fine to remove it?

_(Incidentally I did not find a way for a regular user to change his/her password, this sounds like a surprising oversight!)_

**Comment by muff1nman** [comment]
passwordSettings.jsp seems to imply its still used. @fxthomas you can change your password, but you have to enable it when creating the user. Not sure why one would disable it...

**Comment by EugeneKay** [comment]
I had not noticed the lack of a local password change(all of my users are via LDAP)... that is definitely an oversight. Or am I misunderstanding this report?

Disabling a user's ability to change their password may make sense in some use cases - eg, read-only(children) or semi-public users(demo account).

**Comment by biconou** [comment]
Fixed in #210
