### ISSUE TITLE
Docker Container

### ISSUE THREAD

**Issue by j0nnymoe** [Libresonic/libresonic#161]
Hi, 

I am part of a docker group (LinuxServer.io) and we have created a LibreSonic docker container: https://hub.docker.com/r/linuxserver/libresonic/ (x86_64) & https://hub.docker.com/r/lsioarmhf/libresonic/ (armhf)

We were wondering if you would be interested in having us as an official install method?

Some of our containers are already official install methods for some projects and we have a big list of containers here too: http://tools.linuxserver.io/dockers
Thanks

**Comment by biconou** [comment]
Indeed, Ability to install libresonic as a container is needed.

**Comment by EugeneKay** [comment]
I would welcome a patch to make Docker a target, after the work on Spring-Boot, etc is completed for 6.2.

**Comment by bfkelsey** [comment]
You may want to wait for #62 to be completed too. I don't think docker works well storing a bunch of data on the instance.

**Comment by j0nnymoe** [comment]
@bfkelsey our container is working fine :)

**Comment by muff1nman** [comment]
As mentioned above, feel free to submit a PR for this at any time.

**Comment by aptalca** [comment]
I think there's been some confusion. There is no PR or code change necessary.

LinuxServer.io already built the docker container images, uploaded to docker hub and are maintaining them. They work really well.

What's been suggested is that Libresonic can update their install readme to inform their users that the docker container is an alternate install method.

@muff1nman If you meant a PR to update the install readme, we would be happy to do that.

**Comment by muff1nman** [comment]
No I meant a PR to include the Dockerfile inside of the repository.

**Comment by aptalca** [comment]
LinuxServer.io provides pre-built images distributed via the official docker hub. We build and test the images on/for multiple platforms (x86_64, armhf, aarch64). The containers are based on our own baseimages (alpine or xenial based). We provide support on the docker container side and anything app specific is referred upstream.

We do not provide dockerfiles for users to build the images themselves (that would be a support nightmare).

**Comment by EugeneKay** [comment]
If you will not be providing a dockerfile for this project to self-build an image then there really isn't much more we can do here.

Libresonic is packaged & distributed in WAR format only. Any third-party builds / distributions, such as yours, are not official and will not be linked to. There is not a stated Trademark policy at this time, so you should be fine to continue as-is, but do not purport to be official. If you would like to re-open this discussion please do so in the form of a PR with your dockerfile. Thanks.

**Comment by muff1nman** [comment]
So then what is the goal of this issue? If you all want to maintain a docker image for libresonic, that's awesome, but you don't really need anything from us. As for us calling your image official, I'm afraid that's too much to ask as then we cannot help people using the official image as we don't control the Dockerfile. With that said I'm sure we could put a link to your docker image in the readme somewhere as long as it's clear libresonic doesnt maintain the image.

And just to be clear, I absolutely think it's great you all built the image, not trying to be dismissive, but rather clearly define who it is that will be supporting this image. As long as the dockerfile is not in our repository we won't be supporting it directly and hence won't be calling it official.

**Comment by sparklyballs** [comment]
another linuxserver member here
for any of the projects we build docker images for we don't call ourselves official for any of them
we have links in some readmes etc
