### ISSUE TITLE
How to add multiple folders to Music?

### ISSUE THREAD

**Issue by syaifulnizamyahya** [Libresonic/libresonic#166]
I have multiple music folder.  Command below are what I tried and it failed.

```
-v "/mnt/user/MP3/:/mnt/user/Flac":"/music":rw
```

What is the correct way to issue multiple folder to music?

**Comment by muff1nman** [comment]
Is this for docker?

**Comment by muff1nman** [comment]
Can you give us the command and output?

**Comment by syaifulnizamyahya** [comment]
Yes. Its for docker. Sorry for not mentioning that. Anyway, it is solved by simply adding the parent folder. 

'''
-v "/mnt/user/":"/music":rw
'''

Then in libresonic settings, i just use 
'''
/music/Flac
/music/MP3
'''

Thanks. Libresonic is great!
