### ISSUE TITLE
internet m3u playlist

### ISSUE THREAD

**Issue by jer1956** [Libresonic/libresonic#186]
When using the internet getting m3u playlist URL's using the Lan IP for the server is of no use.  You need the internet URL  the client used to connect via the internet to be used instead.  In my case i use a DDNS service with a domain name.

**Comment by ibmibmibm** [comment]
here's my nginx config for workaround this problem:
```
sub_filter_once off;
sub_filter 'http://$server_addr:[internal port]/' '$scheme://$host/';
sub_filter_types 'audio/x-mpegurl';
sub_filter_last_modified on;
```

**Comment by jer1956** [comment]
Thank you for the suggestion. As i was saving a single playlist for all the movies, i just decided to do a global find and replace to fix it.  The obvious answer is to use the WAN domain users can specify in Settings - Network, and supply m3u with that. An option of Lan or Wan could be added.

**Comment by muff1nman** [comment]
Is this when you use the share button on the playlist?

**Comment by muff1nman** [comment]
This should be fixed now on the develop branch. Please reopen if not.
