### ISSUE TITLE
Q : What is the WapController for ?

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#190]
Does anyone know what is the org.libresonic.player.controller.WapController controller for ?

**Comment by muff1nman** [comment]
Not sure, might be related to https://www.w3.org/TR/NOTE-WAP

**Comment by EugeneKay** [comment]
Not a clue. Delete it and see what breaks?

**Comment by biconou** [comment]
Ok

**Comment by DavidARussell** [comment]
Yeah 'WAP' was used for mobile 'internet' access (sort of) in the pre-smartphone era.

**Comment by fxthomas** [comment]
@DavidARussell is correct. It doesn't even use HTML for describing WAP pages and, at least in France (not sure in other countries) no operator sells WAP plans anymore.

**Comment by biconou** [comment]
Removed in Spring Boot branch.

**Comment by biconou** [comment]
This issue can be closed.
