### ISSUE TITLE
New logo uses non-free fonts

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#192]
Looks like the new logo is using [DIN Condensed](http://www.paratype.com/pstore/default.asp?fcode=PT_DNC&letter=D) which is a non-free font.

There may be some alternatives: [Alte Din](http://www.1001fonts.com/alte-din-1451-mittelschrift-font.html) or [Cabin](https://fonts.google.com/specimen/Cabin+Condensed?selection.family=Cabin|Cabin+Condensed)

I tried updating the logo with these, but my svg skills aren't the best - I couldn't quite achieve the same look: 

![logo_dark svg](https://cloud.githubusercontent.com/assets/1531528/21513657/85bff61e-cc78-11e6-9bb9-c54af6407b37.png)
![logo_light svg](https://cloud.githubusercontent.com/assets/1531528/21513658/85c469e2-cc78-11e6-9a93-f9ad0172c997.png)

the first is Cabin and the second in Alte Din.

**Comment by muff1nman** [comment]
@ttsda would you be able to submit a new PR using free(e.g. SIL Open Font License) fonts?

**Comment by ttsda** [comment]
Hi! I didn't even think about the fonts. sorry!
Once I have some free time I'll find a nice free font and replace all the logos.

**Comment by jooola** [comment]
Any news ? Should i try to do it ?

**Comment by jooola** [comment]
Tryed this with Cabin font : 
![logo-test1](https://cloud.githubusercontent.com/assets/19195485/23531141/4118c710-ffa5-11e6-8947-8de2d667bd4a.png)

**Comment by muff1nman** [comment]
Nice! The rendering looks cleaner than what I was able to accomplish. Can you try it bold and maybe reduce the spacing between the c and the parenthesis?

**Comment by jooola** [comment]
New tests : 
Bold 
and Bold without less spacing

![logo-test2-bold](https://cloud.githubusercontent.com/assets/19195485/23550113/b03fbd5a-000f-11e7-981f-aa3f001f229f.png)
![logo-test2-bold-lessspacing](https://cloud.githubusercontent.com/assets/19195485/23550114/b045b282-000f-11e7-9de4-a0868f0ecbc4.png)

**Comment by jooola** [comment]
Dark and light : 
![logo-set](https://cloud.githubusercontent.com/assets/19195485/23550502/82ee5418-0011-11e7-9b8c-eb1d1d7fb915.png)

**Comment by muff1nman** [comment]
Can you submit a PR with these making sure to update the svgs as well?

**Comment by jooola** [comment]
I will !
No problem

**Comment by jooola** [comment]
Is it ok if i don't build svg from scratch ? I don't know Inkscape, so i only can import the files to convert them to svg ...
The svg pictures still are correct. I'll PR and you will see.
