### ISSUE TITLE
Chat feature using XMPP

### ISSUE THREAD

**Issue by 3615pipou** [Libresonic/libresonic#194]
It might be good to replace the chat feature by an XMPP base one, maybe using https://conversejs.org

**Comment by 3615pipou** [comment]
There is now up to date XMPP hosting services and customable with your own domain name : 
- https://account.conversations.im/domain & https://account.conversations.im
- https://support-en.mailbox.org/knowledge-base/article/introduction-to-jabber
- https://gultsch.de/compliance_ranked.html

**Comment by EugeneKay** [comment]
No.

Per the 6.2 Release Plan, Chat is not Libresonic's job. Implementing XMPP would be a complete nightmare, are you serious?

**Comment by 3615pipou** [comment]
@EugeneKay well the 6.2 is certainly too early. I was not proposing to "implement" XMPP from scratch but to use https://conversejs.org maybe as an easy to install plugin.

**Comment by stevenroose** [comment]
Chat really shouldn't be in Libresonic. I might even advocate for removing it.

**Comment by biconou** [comment]
Agree
