### ISSUE TITLE
Can no longer startup application

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#200]
Can no longer startup application. Using tomcat.

**Comment by biconou** [comment]
Do you mean deploying the libresonic.war.original file into Tomcat 8 ?

**Comment by biconou** [comment]
I reproduced on both tomcat 8 and tomcat 8.5.
On the other hand the standalone package works with 
java -jar libresonic.war

I'll investigate soon.

**Comment by khers** [comment]
For me the tomcat logs complained about a missing file '/db/libresonic.lck'.  I don't know why it would be looking for this in / but when I add a /db symlink to /var/libresonic/db, tomcat will start libresonic again.

**Comment by muff1nman** [comment]
@khers sounds like you are encountering #198. This issue corresponds with the latest from the git develop branch.

**Comment by muff1nman** [comment]
@biconou https://github.com/muff1nman/libresonic/tree/attempt-to-fix

I got the tomcat war starting up again. Though I'm running into some other issues now and need to cleanup some extraneous changes that I was testing with. Just wanted to share what I found working so far. What do you think about removing the entire web.xml and the migration to servlet 3.0 api?

**Comment by biconou** [comment]
@muff1nman That sounds nice. 
I did not review all your modifications bit I saw that you can include jdbcdrivers only in boot profile. Good. 
For servlet 3, sure should but I do not have any Idea; do we need more than changing the provided dependency in pom.xml ?
There are also things left that should be cleaned up. 
- the libresonic-servlet.xml file should be removed.
- the booter project should be thrown away
- We must decide if we still need a assembly project
