### ISSUE TITLE
Folders that contain right single quotation marks are not detected in media scan

### ISSUE THREAD

**Issue by lrvick** [Libresonic/libresonic#207]
To be clear the issue is with the right single quotation mark which is a unicode character. 0x2019

` ’ and ' are all deceptivley similar, but are in fact different characters!

Right single quotation marks are favored in titles tagged with tools like musicbrainz.

Examples of folders libresonic ignores:

"I’m Wide Awake, It’s Morning"
"I wonder What’s Next"

Logs are identical and generate no errors or warnings when folders are ignored. Log output still identical when all of such characters are removed, but suddenly impacted folders then appear in the library and work as expected.

Not tested on Linux. So far only reproduced on FreeBSD/UFS.

**Comment by fxthomas** [comment]
Works perfectly well for me for e.g. [Whatever People Say I Am, That’s What I’m Not](http://musicbrainz.org/release/6fee2d0c-0e3e-3fb1-bdd5-1c8fb7cfe906) by the Arctic Monkeys.

Somebody already had a similar issue with Unicode on FreeNAS in #170, maybe this is related?

**Comment by EugeneKay** [comment]
This may be a unicode path-handling issue with Tomcat under FreeBSD(which is the base for FreeNAS)? I'm not ruling out a Libresonic problem, but its worth checking out.

**Comment by jooola** [comment]
Maybe related to #135

**Comment by muff1nman** [comment]
See #285
