### ISSUE TITLE
Hsql database not getting saved?

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#212]
Seems like the hsql database is not getting saved correctly. I've seen some cases where data seems to get lost. We might need to add this back in:

https://github.com/Libresonic/libresonic/blob/stable/libresonic-main/src/main/java/org/libresonic/player/dao/HsqlDaoHelper.java#L83

**Comment by Japi42** [comment]
I spent some time trying to get to the bottom of this on a new install (which wasn't creating a database on the filesystem at all), and was able to fix it by setting the "spring.profiles.active" property in the application.properties to "legacy".  I have no idea if that is the right fix, but it at least got me up and running.  PR #215

**Comment by muff1nman** [comment]
I haven't been able to reproduce since the fix for #211, so I am closing this.
