### ISSUE TITLE
Deadlock issue when using postgres

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#214]
I tested both subsonic and dsub and they both cannot get past login.

**Comment by plastikman** [comment]
@muff1nman I am using dsub with the latest commits to 6.2.  @EugeneKay I know you are using dsub, can you confirm?

**Comment by muff1nman** [comment]
Looks like a deadlock issue when using postgres. Looks like there is some funky synchronized java nonsense potentially causing the issue.

**Comment by muff1nman** [comment]
Interestingly enough, I'm not sure how we haven't encountered some deadlock with all of the 'synchronized' strewn throughout the codebase. It might make sense to go through and move these to use database transactions instead, I'll have to do some research to see if this is even compatible with hsql 1.8. Also I imagine doing so might improve performance.

**Comment by weirdcrap** [comment]
I'm running LibreSonic 6.1 & not having issues with the SubSonic android app at all.

**Comment by biconou** [comment]
This must be fixed by #217 
Tested with Ultrasonic android app.

**Comment by muff1nman** [comment]
This is not fixed by #217 as this is specifically caused by deadlock within the dao layer.
