### ISSUE TITLE
Standalone Application not properly configured 

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#220]
When running the application in standalone mode it is not initially properly configured. 
See #219

**Comment by muff1nman** [comment]
It seems to be working fine for me, what kind of error are you getting? I don't see how #219 changes much.

**Comment by biconou** [comment]
Yes it works but in standalone mode (ie mvn spring-boot:run) the org.libresonic.player.boot.Application#configure method is never invoqued (in fact it is only invoqued by an external servlet container). Thus, AdditionalPropertySourceConfigurer is ignored. That implies for example that the default spring profile is not LEGACY and then the database is only created embedded in memory. 

My code is intended to refactor the org.libresonic.player.boot.Application#configure method in a way that it is both invoqued by Tomcat or by the main method.
You can see some similar solutions on stackoverflow.

**Comment by muff1nman** [comment]
Yep, this makes sense now. Reproduced as you mentioned.
