### ISSUE TITLE
Potential performance issue 

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#221]
In a previous discussion, @fxthomas mentionned that running Libresonic 6.2 as a standalone app could be slower than when it is deployed to Tomcat.
I would like to investigate that.

@fxthomas could you tell me exactly on what special usecase you noticed this problem ?

**Comment by fxthomas** [comment]
I did two tests and was finally able to pinpoint what felt wrong :

* Hot test: sequential requests by 5 threads as fast as possible :
  * Before: ~40ms average, practically no deviation
  * After: ~50ms average, 15ms standard deviation

* Cold test: sequential requests by 1 thread with 5s sleeps between requests :
  * Before: ~50ms with practically no deviation
  * After: *~700ms* with 800ms deviation (!)

The command I used was a crude benchmarking tool made of `while true; time curl http://localhost:4040/subsonic/main.view?id=xxxx; done`. The server was hit by nothing else while I did the tests, and I set `-Xmx` to 200M.

The first test is perfectly fine, but the second looks wrong, especially for low-traffic sites that are cold more often than not : a browser's usage pattern will look much more like the second case and that's what caught my eye in the first place.

Any ideas? Can you reproduce that?

**Comment by biconou** [comment]
I got some detailed questions. 
What is before and after ? 
Before = Libresonic 6.1 and After = Libresonic 6.2 ?

What is exactly the configuration of before and after (standalone, libresonic booter, deployed in tomcat) ?

In your requests, the parameter id points a special Album of Folder. Was it always the same id ? Was it an id of an album or a folder ?

**Comment by fxthomas** [comment]
>  What is before and after ?

Before is c6ff05fa7a7f21def11cd47b7e4b1d8ea06949c2, right before merging the Spring Boot PR. "After" is one of the most recent commits in develop (3fe8b7c0df0d76a918ba1eae3953f5f14e453eef).

> What is exactly the configuration of before and after (standalone, libresonic booter, deployed in tomcat) ?

I replaced Libresonic Booter with Spring Boot using the legacy profile (embedded HSQLDB database).

> Was it always the same id ? Was it an id of an album or a folder ?

Yes, the same album id. Although I haven't tested other controllers and ids thouroughly they feel similarly slow in the browser most of the time.

**Comment by biconou** [comment]
@fxthomas perfect !
I'll reproduce your configuration and try to find out what's wrong. It might take me some time.

**Comment by fxthomas** [comment]
Additionally, here is a profiler output for a single cURL request going through Libresonic :

![screenshot from 2017-01-14 22-47-48](https://cloud.githubusercontent.com/assets/613594/21958297/89b8f5c2-daab-11e6-9150-b0afa85b5449.png)

There seem to be an issue with how `org.apache.catalina.webresources.Cache` retrieves something from the WAR then evicts it from the cache after ~5 seconds.

**Comment by fxthomas** [comment]
It looks like the messages in the logs I mentioned [earlier](https://github.com/Libresonic/libresonic/issues/142#issuecomment-270233623) and deemed harmless at first glance, are actually a symptom of the same problem.

Apparently [these guys](https://github.com/jhipster/generator-jhipster/issues/3995) have the same issue and mention an interesting point : the default Tomcat cache size is 10M, which is pretty small and gets filled up quite quickly.

**Comment by fxthomas** [comment]
Having configured a very large cache for testing, it is not the single issue. For some reason, every 30s Tomcat _evicts_ all resources from the cache :

![screenshot from 2017-01-15 01-11-03](https://cloud.githubusercontent.com/assets/613594/21959180/b360e4ca-dabf-11e6-86a1-749a827c0a14.png)

...which are then promptly extracted again from the WAR on the next request, defeating the purpose of the cache in this case.

**Comment by fxthomas** [comment]
Well, configuring Tomcat with those 3 things fixed the issue and brought performance back to the same order of magnitude as before :

* Larger resource cache size (400 MB works but may be too much)
* Very large `cacheTtl` setting (e.g. `Long.MAX_VALUE`)
* Disabling Jasper's development mode to prevent JSP from being recompiled

I'll send a PR if you don't see anything wrong with these values.

By the way, the "remember me" checkbox broke again for some reason, any hope of fixing it? It's quite a pain when I have to restart the server this often! :)

**Comment by muff1nman** [comment]
Max long seems a bit excessive. What about something like 24 hours?

I can take a look at the remember me at some point, one of these days we might keep it working ;)

**Comment by fxthomas** [comment]
Fine with me!

I was actually trying to find a way for Tomcat to extract all things beforehand like Jetty does, as it seems sensible to prepare as much as possible before starting to handle requests in a production environment. I wasn't able to find anything unfortunately...

**Comment by biconou** [comment]
well done @fxthomas

**Comment by biconou** [comment]
I added a metric to the application that measures the time of the /main.view request.
This metric can be seen through JMX MBean.
It is high at server startup but continuously decreases.

![metric](https://cloud.githubusercontent.com/assets/5565107/22001834/cfe4916c-dc47-11e6-88ed-f3d3e226d3fb.png)

**Comment by fxthomas** [comment]
Just sent a PR with what my changes.

@biconou I need to look into using JConsole more, this looks really useful!
@muff1nman Thanks for taking care of the remember me :)

**Comment by biconou** [comment]
@fxthomas This metric is something I added. It's not built in. I will propose a PR with that.

**Comment by muff1nman** [comment]
Sounds like this is resolved now
