### ISSUE TITLE
Installation vector outside of tomcat?

### ISSUE THREAD

**Issue by surfrock66** [Libresonic/libresonic#229]
Tomcat has several issues on Ubuntu Server.  For example, right now on Ubuntu Server 16.10, tomcat8 cannot be installed due to this bug: https://bugs.launchpad.net/ubuntu/+source/tomcat8/+bug/1586054

Is there an installation method for libresonic that can bypass tomcat and use an existing apache instance, or a self-contained method that includes specific java servelet dependencies to be run from a standalone installer?

I would like to migrate from subsonic to libresonic but not being able to install without tomcat is somewhat of a non-starter.  I will try to find the time to debug the tomcat installer but this issue has to be impacting other users.

**Comment by muff1nman** [comment]
Tomcat 7 should be satisfactory although java 8 is required. In addition spring boot will be available come 6.2 which runs standalone. No installer, no tomcat, just java 8.

**Comment by surfrock66** [comment]
Ok, that's good to know...I didn't clarify this but tomcat 7 fails to install with the same errors as tomcat 8.

**Comment by muff1nman** [comment]
Huh, well that's a fun ubuntu bug then. Maybe try a real distro like Fedora?  But in all seriousness, many people don't use tomcat as provided by their distribution. Tomcat provides an excellent binary distribution for any OS that I would try. Just download from tomcats site and try it out.
