### ISSUE TITLE
Local Users removed after using latest spring4 work

### ISSUE THREAD

**Issue by plastikman** [Libresonic/libresonic#234]
So I know that this is an "Issue" in the development branch, but I want to make sure we are aware of it.  When I upgraded my non Spring4 development war to spring4 all of my local users disappeared.  

Has anyone else experienced this?  I don't particularly care because I am the only user, but if this is a problem for others it may be a real issue.

**Comment by fxthomas** [comment]
I've seen it a few weeks ago but it was fixed rather quickly.

When Spring Boot loads it says "loading profile" at some point, what does it say after that?

**Comment by muff1nman** [comment]
If we can get this reproduced again, I would be interested in fixing it.

**Comment by plastikman** [comment]
I don't have a backup of my database before the upgrades.  the only way for me to re-create this issue would be to downgrade to 6.1 then update to a beta.

**Comment by muff1nman** [comment]
I think this can be chalked up to an old build affected by #211 since I haven't heard of anyone else being affected by this.
