### ISSUE TITLE
Update stand-alone packages and build docs for Spring Boot

### ISSUE THREAD

**Issue by fxthomas** [Libresonic/libresonic#235]
The stand-alone packages (.deb and .rpm) and documentation need to be updated following the migration to Spring Boot.

EDIT: I was out of date, I just noticed that the packages were completely removed from the main repo by #223. It makes sense to split this to another repo, but right now the docs point to something that doesn't exist anymore.

**Comment by muff1nman** [comment]
I removed the BUILD.md as it was redundant anyways.
