### ISSUE TITLE
Change launch parameters for tomcat version

### ISSUE THREAD

**Issue by lones710** [Libresonic/libresonic#237]
Hello guys, I already enjoy using libresonic. How can launch parameters be changed? I used to change these for subsonic or madsonic in /etc/default/madsonic:

MADSONIC_USER=xxxx
MADSONIC_ARGS="--port=4040 --init-memory=256 --max-memory=1024"

another important thing for /usr/bin/madsonic:

'-Djavax.sound.sampled.SourceDataLine=#PCH [default]' \
  -verbose:gc \
#for jukebox audio output

Edit: I am using libresonic via tomcat

**Comment by muff1nman** [comment]
I can't really talk to your specific tomcat setup, but can talk to the general tomcat binary that you can download from their website. As described [here](http://tomcat.apache.org/tomcat-8.0-doc/RUNNING.txt), you can create a file named `setenv.sh` or for windows `setenv.bat` in the `bin` folder which you can modify the java args. I.e.:

```
$ cat .local/opt/apache-tomcat-8.5.9-libresonic/bin/setenv.sh 
export JAVA_OPTS="$JAVA_OPTS -Dlibresonic.home=/home/andrew/.cache/libresonic-test"
```
We have a todo to improve some of our documentation around this.

**Comment by muff1nman** [comment]
See [CONFIGURATION.md](https://github.com/Libresonic/libresonic/blob/develop/documentation/CONFIGURATION.md).
