### ISSUE TITLE
Rethink "Sharing"

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#238]
Currently, sharing is dependent on url redirection i.e. a subsonic.org concept. Since url redirection is in the process of getting removed from libresonic, sharing needs to be rethought of how it should work, or if it should even be kept at all.

**Comment by afxgit** [comment]
I personally use/like the sharing feature as a quick way for someone to listen to a track without needing to set them up as a user on the system...not sure if I'm a minority on this one here.

**Comment by jooola** [comment]
I would keep the sharing feature ! Not often used but really useful !

**Comment by Tapchicoma** [comment]
Can we add some settings like service DNS name and compose sharing url based on it?

**Comment by muff1nman** [comment]
@Tapchicoma see #239. I could see adding a DNS name setting that is used in cases such as this.

**Comment by rykerwilliams** [comment]
I never used Subsonic as a paid app, just the fork with the licensing removed before it was Libre, so I never shared. I think sharing seems like a nice feature, but I wouldn't miss it.

**Comment by fozzedout** [comment]
A subsonic address is not needed - if you have exposed your libresonic installation to the world, it works with the current exposed location. The share info needs to change to what you set up your external server, but the path of /share/XXXXX works as is. 

The share page has a reference to subsonic, which does need to be removed (and might be in the latest beta, I haven't checked - I'm using a 6.0 version in a docker container)

**Comment by muff1nman** [comment]
Okay I think sharing can be kept as is. The reason why I was concerned is that it was hiding behind the url redirection flag. However, sharing is not dependent on it. Moving forward, I think it is likely url redirection will be removed so then sharing will be enabled by default. If folks want a flag to disable it, that can be done, but really that can be controlled by limiting the ability to create shares on a user by user basis.
