### ISSUE TITLE
Keep Custom URL Redirection?

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#239]
Obviously the redirection service provided from libresonic/subsonic.org should be removed. Currently it is disabled in 6.1 I believe. However, I would like to discuss if keeping the custom url redirection still provides value. It might be useful for things like #186, so that people don't have to customize nginx rules. On the other hand, since we said we won't support [https](https://github.com/Libresonic/libresonic/issues/125#issuecomment-256227104), it might not make sense to have any url redirection either so that it all should be done via nginx.

Thoughts?

**Comment by jooola** [comment]
If you have a simple libresonic backend running peacefully you just have to set up you're reverse proxy to set up SSL and whatever else the only thing is that has to be well documented !
( Reverse proxy may be really more powerful than some options in libresonic ! )
Still "--context-path=" is really useful i think if we don't have a well documented wiki

**Comment by muff1nman** [comment]
I am going to test removing url redirection entirely to rely on the proxy to do this for us.

**Comment by muff1nman** [comment]
I am pretty confident that url redirection can be removed without impacting anything except for Upnp. I'm having mixed thoughts about how to go forward with it at this point. I am toying with the idea of removing the Network Setting tab entirely and then adding an input boxy onto the upnp page that users can input their LAN address that they would like to use for upnp. 

Previously Upnp used the same address as the url redirection address, but I don't think this is actually correct. Since our use case limits Upnp to the local network, interacting with the WAN address makes little sense and in fact may not work on some users networks.

**Comment by muff1nman** [comment]
#260 implements the above.

**Comment by EugeneKay** [comment]
Yes, this feature should be removed as much as possible.
