### ISSUE TITLE
Haproxy reverse proxy configuration don't work for SSL

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#242]
So i tested the Haproxy configuration in the documentation
```
frontend https
    bind $server_public_ip$:443 ssl crt /etc/haproxy/ssl/$server_ssl_keys$.pem

    # Let Libresonic handle all requests under /libresonic
    acl url_libresonic path_beg -i /libresonic
    use_backend libresonic-backend if url_libresonic

    # Change default backend to libresonic backend if you don't have a web backend
    default_backend web-backend

backend libresonic-backend
  server libresonic 127.0.0.1:8080 check
```

And as expected nothing works !
If i use the current settings the server works but same bug as subsonic we have a white home page after login, it is simply empty.
Screenshot : 
![capture d ecran de 2017-02-01 20 08 01](https://cloud.githubusercontent.com/assets/19195485/22522041/64b84b5c-e8ba-11e6-9ddf-fb6eb56d48f4.png)
![capture d ecran de 2017-02-01 20 09 31](https://cloud.githubusercontent.com/assets/19195485/22522043/64c4a06e-e8ba-11e6-8f70-55ef1e13ded8.png)

**This is maybe due to the mixed content of the page not loading.**

With the configuration i wrote last time : 
```
frontend https
    bind $server_public_ip$:443 ssl crt /etc/haproxy/ssl/$server_ssl_keys$.pem

    acl url_libresonic path_beg -i /libresonic
    use_backend libresonic-backend if url_libresonic

    default_backend web-backend

backend libresonic-backend
    redirect scheme https if !{ ssl_fc }
    server libresonic 192.168.122.10:8443 check ssl verfiy none
```
I changed this since we don't have any ssl in the backend
`server libresonic 192.168.122.10:8080 check ssl verfiy none`

And now i have a 503 error, i guess because haproxy is expecting SSL communication but they aren't !

Maybe need to find a working haproxy configuration or integrate a patch to libresonic to fix this.
( simply remove the mixed content problem )
Here is an old patch from subsonic we tryed to add here but i solved the problem with a work around ( not working anymore )
#120 
https://sourceforge.net/p/subsonic/patches/23/

Hope this is enough detailed !

Btw need to change 
```
backend libresonic-backend
  server libresonic 127.0.0.1:4040 check
```
into
```
backend libresonic-backend
  server libresonic 127.0.0.1:8080 check
```
in the current documentation

**Comment by fxthomas** [comment]
I'm strongly against modifying Libresonic code for this : HAProxy is able to proxy an HTTPS request to an HTTP backend just like Nginx or Apache do.

Your original snippet didn't work for me. A quick Google search yields this :

```
frontend https
    bind *:443 ssl crt /etc/certs/cert.pem

    option forwardfor
    http-request set-header X-Forwarded-Proto https if { ssl_fc }

    acl url_libresonic path_beg -i /libresonic
    use_backend libresonic-backend if url_libresonic

backend libresonic-backend
    server libresonic 127.0.0.1:4040 check
```

Can you check on your side and send a clean PR with it?

**Comment by jooola** [comment]
I do understand that adding code isn't the good solution but maybe so need to fix the bug when trying to load the main page.

I tried you're configuration and still don't load the main frame ( nowPlaying.view )

I tried to enable/disable the mixed content protection and is only got it working without protection !
So we can blame the mixed content for this problem !

![capture d ecran de 2017-02-02 00 04 26](https://cloud.githubusercontent.com/assets/19195485/22530344/63f722c6-e8db-11e6-8cd6-ec91bbdb11c5.png)
![capture d ecran de 2017-02-02 00 04 35](https://cloud.githubusercontent.com/assets/19195485/22530345/63fda402-e8db-11e6-8790-d4d7b45c0436.png)

**Comment by fxthomas** [comment]
Can you test the configuration in #243? I started HAProxy for the first time (yay!) and it works for me.

Note that it doesn't fully emulate what Nginx does in `proxy_redirect` — meaning that only `Location` headers are handled, which is fine since I am fairly certain that Libresonic does not use `Refresh`.

**Comment by jooola** [comment]
No sorry can't get it workin, it stops at haproxy restart , the config file isn't right ... I don't understand is copy/pasted in my actual configuration !

I won't work on this today but here is my log :
```

Feb  2 23:52:23 oolsa haproxy[23858]: [ALERT] 032/235223 (23858) : parsing [/etc/haproxy/haproxy.cfg:69] : error detected while parsing ACL 'http' : unknown conv method 'not' in ACL expression 'ssl_fc,not'.
Feb  2 23:52:23 oolsa haproxy[23858]: [ALERT] 032/235223 (23858) : parsing [/etc/haproxy/haproxy.cfg:70] : error detected in frontend 'https' while parsing 'http-request redirect' rule : error in condition: no such ACL : 'http'.
Feb  2 23:52:23 oolsa haproxy[23858]: [ALERT] 032/235223 (23858) : Error(s) found in configuration file : /etc/haproxy/haproxy.cfg
```

**Comment by fxthomas** [comment]
My package manager has HAProxy 1.7, I'll put a warning about this in the PR. If I believe Google, people seem to be using `!{ssl_fc}` instead of `ssl_fc,not`, so I updated that as well since both syntaxes work for me.

Since this "works for me" I recommend you try to read the HAProxy docs and figure out why you get syntax errors if you still get those. Thanks!

**Comment by youkoso** [comment]
Same here. I've setup a simple reverse-proxy with nginx, but can't do anything because of The page at 'https://xxxxxx.net/index.view' was loaded over HTTPS, but requested an insecure resource 'http://xxxxxx.net/musicFolderSettings.view'. This request has been blocked; the content must be served over HTTPS.

**Comment by jooola** [comment]
Wwwoups, damn , maybe we need to fix this in the code ? i mean its just an "s" to add i guess, i don't know anything in libresonic but for a web page its that easy most of the time !

Trying your configuration, i think it will work but , there are lot of configuration lines !

Btw if  `mode http` is in the "default" section i think no need to add it everywhere and as it is added by default when installing haproxy maybe remove it ?!

**Comment by muff1nman** [comment]
@nyetcode Please open a different issue for nginx.

**Comment by jooola** [comment]
I tested you're configuration and it works !
But still i think we can cut some lines off the configuration file , i'll submit a PR where we will discuss about those lines i want to remove !

**Comment by muff1nman** [comment]
Excellent. I am going to close this issue then.
