### ISSUE TITLE
Add Plugin Architecture

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#252]
One of the main reasons I started with Libresonic was that I wanted more power over my music. Libresonic offers much power out of the box, but there are many things that I would like to do that aren't currently possible. For example, I would like to customize how music is imported into my libresonic instance. Perhaps invoke some custom external tagger, check for duplicate music already in the server, organize into appropriate folders, etc.

The above was just an example, but one I think we'll find more and more often. The question is, should all functionality like this be built into libresonic, or should we provide a plugin-like architecture to allow users to customize components of libresonic to their liking?

So with that, I would like to gather opinions on adding a plugin architecture to libresonic. Both UI and backend. I understand this is a big undertaking and not something I could see working on in the near future. However I think it makes sense to see if this is something that we should do. Some possible topics/discussion points are as follows:

- Pros/Cons
- Design/Architecture of building plugins into libresonic
- Distribution model
- Plugin Ideas

**Comment by biconou** [comment]
What do you think of turning to an  OSGi platform like Karaf ? It sounds like a perfect solution for modularization by installing features.

**Comment by muff1nman** [comment]
That seems like too drastic of a change. We dont want to rearchitect everything.

**Comment by biconou** [comment]
Maybe. Just an Idea.

**Comment by fxthomas** [comment]
If we're still brainstorming use case ideas, I'd love to have a way to hook into the scrobble process so that I can store additional statistics about what I listen to! Custom playlist generator plugins would be great as well.

Couldn't we do something similar to how transcoder support currently works? I'm thinking something like having a directory containing executables that take a well-defined input and output format, that we can call with an "Plugins" page in the settings. These could be shell scripts written in any language, although I would personally use Python.

The huge benefit is that we avoid recompiling Libresonic (or the plugin) each time we want to make a one-off change!

**Comment by muff1nman** [comment]
We could do something like that, but it would require adding hook points into libresonic at all of the possible plugin integration points.

It might be interesting to try something like http://docs.oracle.com/javase/7/docs/api/java/util/ServiceLoader.html to allow folks to customize the spring application context directly. We might have to add some basic hook places at various locations in the spring application context startup lifecycle, but once that is in place, plugins have no bound in doing whatever they please. It would pretty much be possible to replace the whole application at that point. The downside is that it would require plugins to use java/spring.

Another thought is that I think it would be best to keep plugins shipped with the application, but in a disabled state. It would simplify distribution. For example, ansible at one point shipped modules external to the application, but then they moved them back in, but labeled the level of support each were at; i.e. Core, community, experimental. Folks would then enable and configure plugins via the libresonic.properties file. Maybe a comma separated list of enabled plugins.

**Comment by muff1nman** [comment]
And actually @fxthomas on an unrelated note, I have done some work that I haven't tried submitting a PR for to use [Lizzy](http://lizzy.sourceforge.net/) for playlist handling. I had wanted to use some extended xspf attributes at the time so refactored lizzy for inclusion in libresonic https://github.com/muff1nman/chameleon. Also a good example of a possible plugin though.

**Comment by biconou** [comment]
I've just heard that Java 9 contains a new "modularization" framework called JigSaw (but don't know more about that).

**Comment by muff1nman** [comment]
It might be good to wait a bit and see how Java 9 modules compare to something like OSGi. @biconou although I initially commented that OSGi would be too large of a change, it might be the only thing which truly allows us to modularize / pluginize libresonic.

**Comment by muff1nman** [comment]
Also I think the servicelocator would be too limited to be useful.

**Comment by codicusmaximus** [comment]
A Plugin architecture would be great.  I for one would love to have support to play back emulated audio formats such as .sid .spc .nsf .vgz and many others.  That's probably many years off but a plugin architecture would sure be a great start towards supporting esoteric file formats!

**Comment by codicusmaximus** [comment]
Why was this closed?  And what is airsonic?  Is there something going on to this project?
