### ISSUE TITLE
Allow ldap auth via rest api

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#258]
When I was fixing up the ldap auth a week or so back I noticed that the REST api stuff uses a different authentication mechanism which makes it so that ldap authentication does not work via the REST api and by extension android apps. We should really change the auth mechanism on the REST endpoints to use the same auth as the rest of the app. This might be work that should be done along with #69.

**Comment by EugeneKay** [comment]
I'm confused; I am using LDAP authentication just fine?

**Comment by muff1nman** [comment]
Via an Android app? That would be surprising.
