### ISSUE TITLE
libresonic-rest-api in develop branch has a different filename to what it is looking for

### ISSUE THREAD

**Issue by Phoenix09** [Libresonic/libresonic#265]
`java.lang.IllegalStateException: java.io.FileNotFoundException: /home/subsonic/subsonic-tomcat/webapps/libresonic/WEB-INF/lib/libresonic-rest-api-6.1.jar (No such file or directory)`

it is actually named `libresonic-rest-api-6.2.beta1.spring4.jar`

**Comment by muff1nman** [comment]
What are you trying to do? This smells like stale artifacts as we recently changed the pom version on the develop branch.

**Comment by muff1nman** [comment]
Haven't heard anything here so closing for now.
