### ISSUE TITLE
Possible bug and information

### ISSUE THREAD

**Issue by dubima** [Libresonic/libresonic#266]
version 6.1
Firstly, i have to get ffmpeg in order to be able to transcode, is this intended?

Playing videos with the web player doesn't allow me to use the time tracker, every video is always 0.00:0.00. Clicking anywhere on the time track restarts the video. Music plays fine and is tracked.

Another thing, subsonic used to open various ports, one i recall is 9412, which looking at the code it is for DeployerService. Now if i bound subsonic to local only that port and the others would ignore and still be accessible via the internet. Libresonic on the other hand, as it's behind tomcat doesn't apart from one port, I can't find it in the code as I'm guessing it's a random port every start, right now it's port 35141, before it was 45676, I'm guessing if restarted then it would be a different port too.

My question to that one is, what's it used for, is it the callback service for url.libresonic.org or for DLNA/UPnP or Sonos or lastfm or ...?

**Comment by dubima** [comment]
Never mind about the time thing, i fixed it, was on my side.
Only the port question left, it's currently open on 41504, due to restarting.

**Comment by muff1nman** [comment]
Good question, and I dont know the answer off the top of my head. We'll have to look into it.

**Comment by muff1nman** [comment]
Took sometime and looked into this. The open ports you see either come from upnp (usually responsible for the random udp port) and from tomcat (various RMI ports from brief readings online). #316 should address upnp, while you can deploy on Jetty if you really dont like tomcat opening those other ports.
