### ISSUE TITLE
Please remove Jamstash from recommended apps

### ISSUE THREAD

**Issue by gerroon** [Libresonic/libresonic#272]
Jamstash site is not secure and by providing the link there you are exposing unknowing people's private listening habits and usernames and passwords. In my opinion the site should be removed until the dev implements https. Until then promoting apps that does not practice basic security is not a good practice in my personal opinion.

I myself clicked on it accidentally. If I knew that it was not running https I would have never clicked on that link if you will.  If you insist it should be promoted at least put another line mentions the site's lack of security.

On top of it jamstash dev can access people's files at least that was my reading. Although he claims he never ever read, access private data although his server does. Even if he does not someone else can target his website and steal all the Libresonic usernames logs etc Or they will just listen the connections.

**Comment by muff1nman** [comment]
I would agree. Us removing the link should prevent anyone from using it.

**Comment by fxthomas** [comment]
Same here!

_(Technically I doubt the Jamstash developper runs a server, the extension can stream directly from your Librsonic instance. You still have to trust the extension, of course!)_

**Comment by biconou** [comment]
I was never convinced to use Jamstash but I consider it was a nice attempt.
The Subsonic UI is worth using. And Android/iOS apps are reach too. 
So, no need of jamstash.

**Comment by muff1nman** [comment]
I wouldn't say there isn't a need for it. We should welcome anyone to build their own Libresonic UI. Rather there isn't a need to promote any UI in particular.

**Comment by gerroon** [comment]
Yeah anyone implementing Libresonic is great but at least they should take basic security seriously given that LetsEncrypt provides free ssl certs there is no excuse to run a site like his on simple http. I use LE on my server and it is great it takes 5 mins to set it up. 

I cant speak for the extension, I do not use Chrome and I have no insight into how those xtensions work.

**Comment by biconou** [comment]
@muff1nman Sorry, I meant no need for **myself**.

**Comment by jooola** [comment]
Why not remove jamstash link from the libresonic "more" page and add a link to an "compatible Apps" page on the wiki ?
That will be way more detailed ! 
And we could clean up the "More" page and merge it with the "About" page.

**Comment by izderadicka** [comment]
Jamstash is client only solution -  nothing is being send to their site -  only client is loaded (html, scripts, images) from there - so it really does not matter if one access jamstash.org via http or https.  BTW jamstash.org can be also accessed via https.
What matters is how Jamstash client communicates with libresonic backend -   where it uses it's REST API.  In Jamstash config you can and should use secure link to your libresonic server (https), then all communication including passwords etc. is encrypted with TLS .    So from this perspective Jamstash is as secure as native web api, when connecting via https or android clients using https.   It's up to the user to assure secure (https) connection to server,  there is nothing special with Jamstash.

Having said that I see no problem in removing or leaving Jamstash link - it's basically client similar to any other so there.   Maybe having wiki page with list of all compatible clients is better option then linking some clients directly from application?

**Comment by texxasrulez** [comment]
Jamstash has a cert issued on Tuesday, January 24, 2017. I had no problems with ssl on their site ..
