### ISSUE TITLE
Libresonic 6.2 Beta1 breaks instances running with jetty.

### ISSUE THREAD

**Issue by hurricanehrndz** [Libresonic/libresonic#279]
Breaks instances that were previously running the war with jetty. Please find an attached log of the error.
[Libresonic.2017.03.06.log.txt](https://github.com/Libresonic/libresonic/files/826225/Libresonic.2017.03.06.log.txt)

The issue is the release does not include the a traditional war anymore like previous releases, instead the war now embeds tomcat.

Issue #142 mentions libresonic.war.original, which was not included in the release that would more than likely fix the issue.

To be honest with you though, I'm perfectly fine with how libresonic is now packaging the war, I believe it is an improvement. I just think there was some documentation missing. After reading issues and merges I was able to discover the architectural changes made to the war and adjust my java command accordingly.

For documentation purposes I'm including [the fix](https://github.com/hurricanehrndz/docker-containers/commit/5cead5fa9e81add61077feef83e48afb6451b2c4) I applied to my docker container in order to get libresonic up and running again.

You will notice in the merge, I no longer use jetty which I'm okay with. In fact, the only reason I used jetty before was because libresonic did not have it embedded like subsonic did. Now that libresonic is embedding tomcat, my need for using jetty no longer exists.

**Comment by muff1nman** [comment]
@hurricanehrndz thanks for the report. It might be more than Jetty affected after looking into the cause.

**Comment by muff1nman** [comment]
With the latest change in develop, libresonic should be deployable to Jetty.

**Comment by hurricanehrndz** [comment]
Thanks
