### ISSUE TITLE
INSTALL Document has bad URL

### ISSUE THREAD

**Issue by texneus** [Libresonic/libresonic#282]
This is trivial, but...

The Install Document (INSTALL.md) has a bad download URL.  The URL points to https://jenkins.zifnab.net/job/libresonic/lastSuccessfulBuild/artifact/.repository/org/libresonic/player/libresonic-main/6.1.beta2/libresonic-main-6.1.beta2.war, which gives a 404 error.

You can downloaded the 6.1 beta 1 from the release repository, but there is no sign of a beta 2 there...

**Comment by jooola** [comment]
I don't know much about who's providing the nightly builds ( i guess its zifnab ?)
Well we are now at 6.2-beta1, which is available in the github releases page
[https://github.com/Libresonic/libresonic/releases](https://github.com/Libresonic/libresonic/releases ).

Hope this is still helpful ! Can't help any further i think

**Comment by muff1nman** [comment]
Should be fixed now, thanks for the heads up.
