### ISSUE TITLE
Spring Boot upgrade from 1.4.2 to 1.4.5

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#287]
The new Jukebox feature I am working on (#276) does not work properly with Spring Boot 1.4.2.
Why ? because the Java Sound services are not loaded using SPI due to strange classpath reasons.
I've seen there were other similar issues on Spring Boot now fixed.

Indeed, it works with Spring Boot 1.4.5.

So, can I request a migration from 1.4.2 to 1.4.5 ?

**Comment by muff1nman** [comment]
Seems reasonable to me; do you want to submit the PR?

**Comment by biconou** [comment]
PR #288
