### ISSUE TITLE
Subsonic logger is boring

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#290]
In javadoc of org.libresonic.player.Logger one can read : 

>  Note: Third party logging libraries (such as log4j and Commons logging) are intentionally not
>  used. These libraries causes a lot of headache when deploying to some application servers
>  (for instance Jetty and JBoss).
> 

I do not agree. 

I propose to use slf4j as logging API without having to rewrite all log statements.

We could deprecate org.libresonic.player.Logger and redirect every of its methods to log using slf4j.

**Comment by muff1nman** [comment]
The biggest problem I foresee with this is still logging to ${libresonic.home}/libresonic.log. It'll be a bit of a pain with slf4j. It might be possible to reimplement the same logic we use to decide where libresonic.home is using logbacks [conditional logic](https://logback.qos.ch/manual/configuration.html#conditional). But then we have to deal with the directory not being created at the time the logger starts running. Perhaps there is some programmatic configuration we can do...

Then again, maybe we just stop using libresonic.log all together and throw it all to stdout. Thats where all the other logs are going anyways. Maybe we just cleanup stdout a bit and put everything there?

**Comment by fxthomas** [comment]
Is it possible to both store log entries in `libresonic.log` _and_ output them to the standard stream? The log file is cleared everytime Libresonic restarts, which makes it hard to keep traces in case I need them.

**Comment by muff1nman** [comment]
Outputting to both places should be possible. The biggest hurdle is outputting to libresonic.log before we know where the home directory is and where it's placed at. I'll fiddle with it because what you describe would be ideal.

**Comment by muff1nman** [comment]
The programmatic logback configuration might be nifty. However, it is a bit complex to setup with spring-boot, so this is probably going to have to wait until after 6.2

**Comment by muff1nman** [comment]
Scratch that last comment, it turned out not complicated at all :)

**Comment by biconou** [comment]
Thanks @muff1nman
