### ISSUE TITLE
api access libresonic 6.2beta1

### ISSUE THREAD

**Issue by tob123** [Libresonic/libresonic#306]
Hi,
libresonic works very well! just encountered some issue accessing the api via curl as described here: http://www.subsonic.org/pages/api.jsp
setup: 
* hurricane's docker image https://hub.docker.com/r/hurricane/libresonic/
* libresonic 6.2beta1
running curl to accss the api gives:
----------------------------------------------------------------------
`curl -v 'http://localhost:4040/rest/ping?u=admin&p=test&v=1.13.0&c=test1234tob'`
`* Trying 127.0.0.1...`
`* Connected to localhost (127.0.0.1) port 4040 (#0)`
`> GET /rest/ping?u=admin&p=test&v=1.13.0&c=test1234tob HTTP/1.1`
`> Host: localhost:4040`
`> User-Agent: curl/7.50.1`
`> Accept: */*`
`> `
`< HTTP/1.1 302 `
`< Set-Cookie: JSESSIONID=9C4E9E05655387A2B64574D1B8D25832;path=/;HttpOnly`
`< X-Content-Type-Options: nosniff`
`< X-XSS-Protection: 1; mode=block`
`< Cache-Control: no-cache, no-store, max-age=0, must-revalidate`
`< Pragma: no-cache`
`< Expires: 0`
`< X-Frame-Options: SAMEORIGIN`
`< Location: http://localhost:4040/login`
`< Content-Length: 0`
`< Date: Mon, 20 Mar 2017 08:13:15 GMT`
`< `
`* Connection #0 to host localhost left intact`
----------------------------------------------------------------------
SO I guess the libresonic server is redirecting me to the login page here. i tried other options for the password (encrypted variant, salt token method) but all gave the same result. ALso when i enter the url in the browser I get the following results:
if i have already authenticated against libresonic api access is ok
if i have not authenticated yet against libresonic i get redirected to the login page
dsub (running on my phone) can access all libresonic feautres (which also uses the api a lot)

anything you can recommend how to fix this ?

**Comment by biconou** [comment]
Did you build Libresonic from the up to date /develop branch ? 
I did not study your message in details but I've fixed a similar problem a long time ago. 
My libresonic API works perfectly well both in unit test and from an android app.

**Comment by muff1nman** [comment]
Try this:

```
curl -v 'http://localhost:4040/rest/ping.view?u=admin&p=test&v=1.13.0&c=test1234tob'
```

**Comment by tob123** [comment]
biconou: i just grabbed the container from docker hub. in the about screen i see:
`Version	6.2.beta1 – March 5, 2017`
`Server	Apache Tomcat/8.5.6, java 1.8.0_121, Linux (96.1 MB / 293.0 MB)`
muff1nman:
running the command you indicate produces the error as i explained above.
`curl -v 'http://localhost:4040/rest/ping.view?u=admin&p=test&v=1.13.0&c=test1234tob'`

```
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4040 (#0)

> GET /rest/ping.view?u=admin&p=test&v=1.13.0&c=test1234tob HTTP/1.1
> Host: localhost:4040
> User-Agent: curl/7.50.1
> Accept: */*
> 
< HTTP/1.1 200
< Set-Cookie: JSESSIONID=4C9BB27EFA1B8E2F18E786850F09EC64;path=/;HttpOnly
< Access-Control-Allow-Origin: *
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< Cache-Control: no-cache, no-store, max-age=0, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: SAMEORIGIN
< Content-Type: text/xml;charset=UTF-8
< Content-Length: 127
< Date: Tue, 21 Mar 2017 08:00:27 GMT
<
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response xmlns="http://libresonic.org/restapi" status="ok" version="1.13.0"/>
* Connection #0 to host localhost left intact

```

**Comment by muff1nman** [comment]
@tob123 that is not an error. You got a 200 response which is what is expected.

**Comment by tob123** [comment]
dear people. you are 100% right! thank you a bunch for this superb work of code and support!

**Comment by tob123** [comment]
do you accept donations ?

**Comment by muff1nman** [comment]
Awesome, I'll close this then. We dont currently have a general libresonic donation spot (perhaps we can do this in the future). Personally, if you like my work, you can find me on [keybase.io/muff1nman](https://keybase.io/muff1nman) where you can find my bitcoin address, or my monero address in the pub kbfs [https://keybase.pub/muff1nman/monero.txt](https://keybase.pub/muff1nman/monero.txt).
