### ISSUE TITLE
haproxy reverse proxy configuration with SSL not working for web player

### ISSUE THREAD

**Issue by drinn** [Libresonic/libresonic#317]
I setup a haproxy reserve proxy with SSL today according to the most current documentation and am having a problem getting items to play via the web player.  The setup allows me to browse my library just fine, but trying to play a song in the browser causes the following error in the console in Chrome:

`Mixed Content: The page at 'https://example.com:1234/libresonic/index.view' was loaded over HTTPS, but requested an insecure plugin data 'http://example.com:1234/libresonic//stream?player=3&id=17889'. This content should also be served over HTTPS.`

Similarly, on the right hand column of "Now Playing" when I have my Android DSub app streaming music via libresonic, I get broken image links to what that player is listening to with similar error messages:

`Mixed Content: The page at 'https://example.com:1234/libresonic/index.view' was loaded over HTTPS, but requested an insecure image 'http://example.com:1234/libresonic//avatar.view?id=0'. This content should also be served over HTTPS.`

**Comment by jooola** [comment]
This isn't a haproxy issue but a libresonic code issue.
But could you past here your haproxy configuration please ?

**Comment by muff1nman** [comment]
@joola what makes you think this is a libresonic code issue? Please do not make statements like these unless you are familiar with the code base.

**Comment by muff1nman** [comment]
My guess is that X-Forwarded-Proto is not being set correctly but will verify in the next couple days

**Comment by drinn** [comment]
My haproxy.conf file is as follows:

```
global
        tune.ssl.default-dh-param 4096

defaults
        mode http

frontend https
        timeout client 10000ms
        bind :80
        bind :443 ssl crt /path/to/libresonic.pem
        acl is_libresonic path_beg -i /libresonic
        use_backend libresonic-backend if is_libresonic

backend libresonic-backend
        timeout connect 5000ms
        timeout server 10000ms
        http-response replace-value Location ^http://(.*)$ https://\1
        redirect scheme https if !{ ssl_fc }
        server libresonic 127.0.0.1:1234 check
```

The extra variables were mostly included because running an:

`haproxy -c -f [config]`

Would yield errors without them.

**Comment by muff1nman** [comment]
I imagine we need to add something like this to the haproxy config (not tested):

```
reqadd X-Forwarded-Proto:\ https
```

**Comment by jooola** [comment]
@muff1nman I tried the configuration and it worked for me, i can double check tomorrow ! Thats why i sayd ( a bit to fast ) that the problem come from code ... sorry

I had `reqadd X-Forwarded-Proto:\ https` in my frontend.

@drinn Here is my haproxy configuration : 
```
global
       # Some default configuration
	tune.ssl.default-dh-param 2048
	maxconn 1024

defaults
       # Some default configuration
	option forwardfor
	option http-server-close

########################

frontend main
	bind *:80
	bind *:443 ssl crt /path/to/cert.pem
	reqadd X-Forwarded-Proto:\ https

        acl is_libresonic path_beg -i /libresonic
        use_backend libresonic_backend if is_libresonic

########################

backend libresonic_backend
        http-response replace-value Location ^http://(.*)$ https://\1
        redirect scheme https if !{ ssl_fc }
        server libresonic 192.168.122.20:8080 check 

########################
#EOF
```

**Comment by drinn** [comment]
@muff1nman Thanks for the tips!  After your hints for `reqadd X-Forwarded-Proto:\ https`, I went back and reread the comments at the top of the documentation and was able to get things working with haproxy using the following for "frontend" in my "haproxy.conf":

```
frontend https
        timeout client 10000ms
        bind :80
        bind :443 ssl crt /path/to/libresonic.pem
        reqadd X-Forwarded-Host:\ fronend.example.com:1234
        reqadd X-Forwarded-Proto:\ https
        acl is_libresonic path_beg -i /libresonic
        use_backend libresonic-backend if is_libresonic
````

Where frontend.example.com is the host that I'm connecting to in my browser via SSL.  The backend section of the config didn't need to be modified at all.  Once I made that change, all of the errors in the console went away and I'm able to both use the web player and see those images that were once broken with haproxy and SSL.

I proposed a change to the documentation to reflect what worked for me:

https://github.com/drinn/libresonic/commit/835bbbc0a5aba5d2ee2ef91f5a1d9f3b678955fc

Thank you for your help!

**Comment by muff1nman** [comment]
@drinn, incorporated those changes. Thanks!

**Comment by joshuaboniface** [comment]
I have two suggestions to make regarding the docs related to this:

First, `redirect scheme https if !{ ssl_fc }` should likely go in the frontend section - I don't agree with the logic in 002275468a6fa8e48b7b837fbb5eb4135af79a89 because doing this in the frontend makes more sense in a multi-backend environment (less duplicate lines) and makes no functional difference otherwise.

Second, I would suggest we replace the hardcoded URL and `reqadd` statements with a more dynamic and robust `http-request set-header` version:
```
http-request set-header X-Forwarded-Host %[req.hdr(Host)]
http-request set-header X-Forwarded-Proto https
```

`%[req.hdr(Host)]` makes it fully dynamic; for the basic config here, the end result is the same and a little cleaner, but this is absolutely essential in a multi-domain situation (as is my, admittedly very complex, HAProxy config).
