### ISSUE TITLE
6.2B2: Broken Pipe when playing in web browser

### ISSUE THREAD

**Issue by texneus** [Libresonic/libresonic#323]
I am getting a "Broken Pipe" error in the Libresonic logs when attempting to play a file in the web player in 6.2 beta 2.  The track does not play, no error or any other symptom is apparent in the web interface.  I have actually been unable to play a track in the web browser since at least 6.2 beta 1 but assumed until this point my web browser ad & flash filters were to blame (even though nothing plays even after disabling them).

Relevant portion of the log files attached.  Full log file is included with issue #321.  Possibly this is related to issue reported near the end of #319 (same outward symptom, but the logs show that transcoding does occur and this is a "vanilla" install).

[Log Excerpt.zip](https://github.com/Libresonic/libresonic/files/880824/Log.Excerpt.zip)

Edit:  Removed raw log text and substituted zip file ... sorry 'bout that!

**Comment by joshuaboniface** [comment]
I'm seeing these as well, but in my case they're `org.apache.catalina.connector.ClientAbortException: java.io.IOException: Connection reset by peer` errors, and they don't seem to actually affect my playback from what I can tell.

**Comment by muff1nman** [comment]
This has been going on for quite some time now. I've dug into it once or twice but so far as I can tell its a nuance of jwplayer. As @joshuaboniface said, it doesn't affect playback and furthermore only seems to happen on firefox. I think it makes more sense to get #45 done than spend too much time tweaking jwplayer.

**Comment by texneus** [comment]
BUT, it does seem to affect playback in that nothing plays.  Honestly it doesn't affect me since I don't play in the browser.  I also completely agree 45 is the way to go and should fix this.  I will close as this appears to be a work in progress covered by another issue.
