### ISSUE TITLE
Access to media is open to unauthenticated users   via  /stream URL

### ISSUE THREAD

**Issue by izderadicka** [Libresonic/libresonic#326]
Libresonic 6.2.beta2 – March 24, 2017

Access to URL `https://my.server/libresonic/stream?player=1&id=717`   is not authenticated and is open for everybody.  Thus anybody can easily scan and download my media collection.  
Just by listing  id from 1 to some maximum number (as id is assigned sequentially and for each successful response download media, anyone has access to my  full collection.

I think this is considerable security issue.

Current version of subsonic has solved it by adding auth parameter to  URL query string , which contains some kind of user authentication token.

**Comment by muff1nman** [comment]
We may need to get creative with this so that sharing, Sonos and upnp isn't broken. Perhaps for those cases we use JWT as hinted at. It's not exactly an easy change, so might be a bit of a stretch to get this into 6.2. It might be worth delaying 6.2 just for this. @eugenekay thoughts?

**Comment by izderadicka** [comment]
For UPnP/DLNA  ( and I guess for Sonos too) the intended use in on local LAN -  so this can be streamed over http locally with full access.  My concern is if I enable https access to libresonic ( and open port on my router). nothing should be accessible without proper authentication.  

Looking into dwr response for PlayQueueService.play.dwr there are actually two keys for stream - streamUrl and remoteStreamUrl -   my understanding would be that streamUrl is for local LAN only (and can be used in DLNA etc.) and remoteStreamUrl is for access over Internet - in this case I'd expect some authentication token. So there could be an utility to distinguish between local links and remote links? But current subsonic seams to user token for both, which may not be needed, as least from my perspective,

Also URL `/coverArt.view?id=742` has exactly same issue it's openly accessible to everybody.

**Comment by muff1nman** [comment]
I really dislike the distinction between local and remote. I feel like it's too opinionated on the security model and fragile. I'd rather have everything be secure by default than having local be less secure than remote. Complexity is the biggest enemy of security.

**Comment by muff1nman** [comment]
In develop now so am closing this as resolved, but please do test and verify.
