### ISSUE TITLE
Status page shows broken images

### ISSUE THREAD

**Issue by binhex** [Libresonic/libresonic#333]
When clicking on the Status link in the top menu i see 4 broken images (graphs i assume?), right clicking on a broken image and selecting open image in new tab returns a java stack trace.

libresonic version:- 6.2.beta2 – March 24, 2017

link to image showing the issue:- 
![screen shot 2017-04-04 at 11 58 34](https://cloud.githubusercontent.com/assets/1121837/24653532/154513ee-192e-11e7-8e66-dc1dcf8b406f.png)

link to pastebin with stack trace:- https://pastebin.com/S4CpqL2w

**Comment by muff1nman** [comment]
Are you adding any arguments to your java startup parameters? This is something that is more related with your java environment and is out of libresonic's control.

**Comment by binhex** [comment]
hi muff1nman, thanks for the reply, here are the parameters i use to start libresonic, anything look bad?:-

`# define java settings passed to libresonic
LIBRESONIC_HOST="0.0.0.0"
LIBRESONIC_PORT="4040"
LIBRESONIC_HTTPS_PORT="4050"
LIBRESONIC_CONTEXT_PATH="${CONTEXT_PATH}"
LIBRESONIC_HOME="/config"
LIBRESONIC_MIN_MEMORY="256"
LIBRESONIC_MAX_MEMORY="2046"
LIBRESONIC_PIDFILE=""
LIBRESONIC_DEFAULT_MUSIC_FOLDER="/media"
LIBRESONIC_DEFAULT_PODCAST_FOLDER="/config/media/podcast"
LIBRESONIC_DEFAULT_PLAYLIST_FOLDER="/config/playlists"
LIBRESONIC_WAR_PATH="/opt/libresonic/libresonic.war"

# run java pointing at libresonic war file with defined settings
java -Xms"${LIBRESONIC_MIN_MEMORY}"m -Xmx"${LIBRESONIC_MAX_MEMORY}"m\
  -Dserver.host="${LIBRESONIC_HOST}" \
  -Dserver.port="${LIBRESONIC_PORT}" \
  -Dserver.contextPath="${LIBRESONIC_CONTEXT_PATH}" \
  -Dlibresonic.home="${LIBRESONIC_HOME}" \
  -Dlibresonic.host="${LIBRESONIC_HOST}" \
  -Dlibresonic.port="${LIBRESONIC_PORT}" \
  -Dlibresonic.httpsPort="${LIBRESONIC_HTTPS_PORT}" \
  -Dlibresonic.contextPath="${LIBRESONIC_CONTEXT_PATH}" \
  -Dlibresonic.defaultMusicFolder="${LIBRESONIC_DEFAULT_MUSIC_FOLDER}" \
  -Dlibresonic.defaultPodcastFolder="${LIBRESONIC_DEFAULT_PODCAST_FOLDER}" \
  -Dlibresonic.defaultPlaylistFolder="${LIBRESONIC_DEFAULT_PLAYLIST_FOLDER}" \
  -Djava.awt.headless=true \
  -jar "${LIBRESONIC_WAR_PATH}"`

**Comment by muff1nman** [comment]
Try removing `java.awt.headless`

**Comment by muff1nman** [comment]
http://www.oracle.com/technetwork/articles/javase/headless-136834.html is relevant here and suggests that fonts should still be available even in headless mode. 

Can you confirm that you're using Oracle Jre? You're not using openjfk headless or anything right?

**Comment by muff1nman** [comment]
Also, what distribution are you running? Do you have a package called `fontconfig` installed?

**Comment by binhex** [comment]
i have libcups and fontconfig installed, i am using jre8-openjdk-headless, im assuming from your comment this isnt supported and i should instead switch to oracle jre?.

The distro im running is Arch Linux 64bit, thanks for your feedback so far, its appreciated.

**Comment by binhex** [comment]
OK decided to just give oracle jre a whirl whilst waiting your reply and it worked a treat, no broken graphs, so im happy enough to close this issue, thanks for your help.

**Comment by muff1nman** [comment]
Openjdk is supported but not openjdk headless.

**Comment by binhex** [comment]
ahh got it, thanks for the clarification.
