### ISSUE TITLE
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource

### ISSUE THREAD

**Issue by NHellFire** [Libresonic/libresonic#338]
Just tried a clean install of the develop branch (678c3a7cd3ff3d213adbc354efd098c1d166bf93) and it's crashing on startup. Full log attached.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'springSecurityFilterChain' defined in class path resource [org/springframework/security/config/annotation/web/configuration/WebSecurityConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.servlet.Filter]: Factory method 'springSecurityFilterChain' threw exception; nested exception is java.lang.NoSuchMethodError: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.frameOptions()Lorg/springframework/security/config/annotation/web/configurers/HeadersConfigurer$FrameOptionsConfig;
<snip>
Caused by: java.lang.NoSuchMethodError: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.frameOptions()Lorg/springframework/security/config/annotation/web/configurers/HeadersConfigurer$FrameOptionsConfig;
	at org.libresonic.player.security.GlobalSecurityConfig$ExtSecurityConfiguration.configure(GlobalSecurityConfig.java:95) ~[classes/:6.2-SNAPSHOT]
```

The JDBC error later on is caused by:
```
06-Apr-2017 17:53:04.302 WARNING [main] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.hsqldb.jdbcDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
```
I'd guess that'd go away once the startup issue is fixed.

[libresonic.txt](https://github.com/Libresonic/libresonic/files/903362/libresonic.txt)

**Comment by muff1nman** [comment]
Tomcat, jetty, standalone? Java version? Thanks

**Comment by NHellFire** [comment]
Oops, lost that when I was editing. It's running under Tomcat 8. Just tried standalone and get the same exception.

**Comment by muff1nman** [comment]
How did you build the war? Exact command line please.

**Comment by NHellFire** [comment]
`mvn package`
Nothing else.

**Comment by NHellFire** [comment]
`mvn package`
Nothing else. Using OpenJDK 1.8.0_121, maven 3.3.9

**Comment by muff1nman** [comment]
Try this:
```
mvn clean package
```

**Comment by muff1nman** [comment]
My thought process is, that method its complaining about frameOptions() has been around for a while [now](https://github.com/spring-projects/spring-security/blame/master/config/src/main/java/org/springframework/security/config/annotation/web/configurers/HeadersConfigurer.java#L416), and chances are there are some competing classes on your classpath from a previous build that should be removed with a `mvn clean`.

**Comment by muff1nman** [comment]
0902a6c

**Comment by NHellFire** [comment]
Yep, that works. Can't believe I forgot to try clean.

**Comment by muff1nman** [comment]
Well to be fair, our documentation wasn't exactly helpful in that regard either..
