### ISSUE TITLE
Please add caching headers for /script and /dwr

### ISSUE THREAD

**Issue by masterblaster79** [Libresonic/libresonic#339]
I noticed, that caching is disabled for the /script and /dwr URL path. This leads to a missive bandwith waste.

For example, each of this scripts is loaded 6 times on the start page:
```
/script/jquery-ui-1.11.1.min.js (233KB)
/script/jquery-1.7.1.min.js (92KB)
/script/jquery.contextMenu.js (64KB)
```

The same for the /dwr URLs (e.g. /dwr/engine.js).

Can you remove these headers?
```
Cache-Control:"no-cache, no-store, max-age=0, must-revalidate"
Expires:"0"
Pragma:"no-cache"
```

And add:
`Cache-Control:"max-age=36000"`
(or even higher)

Apart from that Libresonic is just a great piece of software, keep going!

Regards.

**Comment by masterblaster79** [comment]
Does anything speak against also caching the "/coverArt.view?" and "/avatar.view?" requests?

**Comment by muff1nman** [comment]
Yes, this is something I've been meaning to look into. It's definitely a problem. I'm almost wondering if we should include a version in the static files url so that we can bump the cache timeout really high but still have new versions work correctly.

**Comment by muff1nman** [comment]
b6544e6738cef536c78af7e20248382ee2e0cd87
60248477f6b467bdfd4f2b6f2af0a807f479b305

I think bumping the cache time will have to be something that is done with immutable urls as described earlier.

**Comment by masterblaster79** [comment]
>  I think bumping the cache time will have to be something that is done with immutable urls as described earlier.

Agreed.
Anyway, even short cache times of /script improve page load significantly, so I am happy with b6544e6 for now.
Thanks a lot!

**Comment by masterblaster79** [comment]
Hi muff1nman.

I just noticed, that also the /flash/jw-player-5.10.swf isn't cached.
For some reason I don't understand, the IE even fetches it twice on page load.

Cheers!
