### ISSUE TITLE
no war file attached to release 6.2 beta 3

### ISSUE THREAD

**Issue by binhex** [Libresonic/libresonic#342]
Hi ive just noticed there isn't any war file for the latest beta release on github (https://github.com/Libresonic/libresonic/releases/tag/v6.2.beta3) is there are particular reason for this, are you guys not compiling the war file now or was this simply a mistake?.

**Comment by muff1nman** [comment]
That would be a mistake. Thanks for pointing it out!

**Comment by muff1nman** [comment]
Should be there now.

**Comment by binhex** [comment]
Sorry for the delay in posting back, just to confirm the war file worked fine, thanks for fixing up the release.
