### ISSUE TITLE
6.2b2: can't "browse by tags"

### ISSUE THREAD

**Issue by paride** [Libresonic/libresonic#355]
With both the Android apps DSub (the outdated version available in FDroid) and Audinaut I can't browse the library "by tags": the albums do not show up. In Audinaut this is actually the only available option. Both the apps work fine with the proprietary Subsonic.

**Comment by EugeneKay** [comment]
I am unable to reproduce this issue on the demo site.

If you would like to re-open this issue, please upgrade to the current DSub(available on Google Play), include `adb lolcat` debug output, and your libresonic.log. A publicly-accessible test instance would also be very helpful.
