### ISSUE TITLE
move upstream branch from sourceforge to github

### ISSUE THREAD

**Issue by ledyba** [Libresonic/libresonic#36]
Hello!

It looks that the repository of original subsonic moved from [sourceforge](https://sourceforge.net/p/subsonic/code/HEAD/tree/) to [github](https://github.com/sindremehus/subsonic).

How about tracking this new github repo. as upstream instead of old sourceforge repo.?

**Comment by EugeneKay** [comment]
Wow, this is news to me! I'll check it out this week.

**Comment by saintfrater** [comment]
Version 6 is now official... did you release it also ?

**Comment by Micdu70** [comment]
@saintfrater I don't think it will be a new release here because since Subsonic 6.0, this software is not open-source...

**Comment by EugeneKay** [comment]
It looks like new development(after version 5.3) in the upstream will no longer be open-source. This is questionable, as the original license specified was GPL and other authors besides Sindre Mehus have contributed code. I do not believe that going closed-source for releases in that manner is allowable, but I do not have the resources to fight it.

If no further changes will be coming down from upstream then I will review the CONTRIBUTING policy for this repo and look into making it a full-fork+rebrand(eg, to LibreSonic). This is not an optimal solution as far as I'm concerned, but I will continue to support this software for my own internal usage indefinitely and make those efforts available to the community regardless.

The 6.0-beta1 that is currently out under Releases is in a usable state, and contains the majority of what I believe is in upstream's official 6.0. You can use that while a path forward for this project is determined.

**Comment by EugeneKay** [comment]
I have opened https://github.com/sindremehus/subsonic/issues/1 with the Upstream repo to hopefully clarify the situation. Please refrain from dogpiling, etc, so that it can remain a constructive discussion.

**Comment by craftyguy** [comment]
I have alerted the [FSF](fsf.org) to the possible GPL violations with other authors that contributed code under GPL. It's doubtful it'll result in any legal recourse if Sindre Mehus is actually misusing the license, however they have a loud voice and may alert/warn others of subsonic's shenanigans.

**Comment by EugeneKay** [comment]
Based upon the feedback from Upstream, my next step will be to rebrand/Fork the project. I'll leave this Issue open until that process begins(hopefully this weekend).
