### ISSUE TITLE
Consolidate documentation

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#374]
Currently there is `/documentation` in this repo and also the github.io page

**Comment by jooola** [comment]
The documentation in the repo is up to date compared to the website. But the website documentation has better format for jekyll. I'm going to update the website docs and then we will see what we can do.

**Comment by muff1nman** [comment]
Rather than trying to keep them in sync, it would be better just to have a single spot to update

**Comment by jooola** [comment]
Sure ! but before removing one docs from repo or website I prefer have them both up to date.
And delete the useless one after i've done this.

**Comment by jooola** [comment]
I don't know if we should split Dev documentation and the basic documentation ?
I think they are some files for devs we don't on the website.
Any suggestion ?

**Comment by muff1nman** [comment]
Let's keep the dev doc in this repo

**Comment by jooola** [comment]
Ok I think my current documentation is updated, so could be create the documentation/wiki repo ?

I guess i need your help @EugeneKay ?!

**Comment by muff1nman** [comment]
What is wrong with the current libresonic.github.io repo?

**Comment by jooola** [comment]
Well didn't we say that we will create a separate repo for documentation ? submoduled into the website and the software repos ?

**Comment by muff1nman** [comment]
oh okay, I'm following now. Sounds fine to me

**Comment by jooola** [comment]
Website wiki is ready to be submoduled ! Where i don't know but it is ready !

**Comment by EugeneKay** [comment]
I have moved documentation/ into a [dedicated repository](https://github.com/Libresonic/documentation) and created DOCUMENTATION.md outlining where to find docs. This repo can be included as a submodule(for the website) or referenced as needed. I would prefer not to put a submodule in this repo(the player codebase) unless there is a technical reason?

@jooola expressed an interest in maintaining the documentation, so I have arbitrarily put him in charge. Have fun!

**Comment by muff1nman** [comment]
Only reason to submodule here is so people who clone this repo have easy access to the docs IMO

**Comment by jooola** [comment]
So we are going to submodule the documentatio, into the website only ?

**Comment by muff1nman** [comment]
@jooola doc repo is good I think. So should I submodule it into https://github.com/Libresonic/Libresonic.github.io/tree/master/pages/docs? Is there any content of value there that we need to move over first?

**Comment by jooola** [comment]
@muff1nman Actually I think none of use understand each other...

We need to keep the website documentation and replace the current documentation with it.
The website docs is the same as the current documentation docs.

The only thing that changes if the format of the md files. Which is needed for the website to work properly.

So i suggest we move the docs from the website over to the documentation repo, and then we submodule it. All this with a big "documentation refactor" and a "documentation submodule" commit.

**Comment by muff1nman** [comment]
Although this is still in progress, I think the discussion can now be moved over to the documentation side and the PR we have open over there.
