### ISSUE TITLE
Crash when accessing Sonos settings

### ISSUE THREAD

**Issue by blu-k** [Libresonic/libresonic#377]
Hello.
I was using an older version of Libresonic the last couple weeks and was very satisfied.
Today I tried to use the new 6.2 release, and it seems to run fine at first.
But when switching the enable button on the Sonos settings or changing the service name it crasehs.

I am running OSX El Capitan with Tomcat as described here: https://maltronic.io/2016/01/14/easily-install-apache-tomcat-on-mac-os-x-10-11-el-capitan-with-homebrew/
FFMPEG 3.3 is installed from https://evermeet.cx/ffmpeg/

Here is the log from the crash:

[crash.txt](https://github.com/Libresonic/libresonic/files/974719/crash.txt)

Any idea what could have caused this or how I could help out?

Best regards

**Comment by muff1nman** [comment]
Wasn't able to reproduce but I have a hunch on what could have caused it and wrote up a potential fix at #378. The best help would be to see if that fixes the problem for you. Do you think you could do that?

**Comment by blu-k** [comment]
Yes, this seems to fix the issue. Thank you.

Here is how I built the war: (it was my first time, so just asking if I did it correctly) 
[libresonic_buildlog.txt](https://github.com/Libresonic/libresonic/files/976119/libresonic_buildlog.txt)

**Comment by muff1nman** [comment]
Yes that looks good. I'll merge that change into stable.
