### ISSUE TITLE
Migrate from packaged version to standalone war

### ISSUE THREAD

**Issue by dorel14** [Libresonic/libresonic#381]
Hello 
Befor wehn changing version of libresonic , i had to make a .deb file , I see now its more simple with the war file and an .sh file to run it , 
I've tried to downoload et test 6.2 => it ok but hoxw can i migrate my db from my old libresonic to the new one ? just move the file ,
Another question is => if i want to run with an external db is it possible to migrate the old db to the new one because i don't want to lose everything ?

Thx for your answers

**Comment by muff1nman** [comment]
The db file is automatically migrated provided you set `libresonic.home` correctly

Inter-database migrations are out of scope for libresonic. It may be doable using a database migration tool.

**Comment by biconou** [comment]
If you planned to keep the same db solution (the legacy solution is embedded file HSQLDB instance) nothing is required. Keep the db files as is. Note that in case you came from Subsonic, the db  files must be renamed from subsonic.* to libresonic.*.

If you plan to turn to an external db solution based on something different from HSQLDB, you will have to migrate your datas. 
I planned to migrate to postgresql, and I will probably use Talend to write a migration program. If so, I'll perhaps submit it as an example tool.
