### ISSUE TITLE
Playback error with libresonic 6.2 and DSub

### ISSUE THREAD

**Issue by shagr4th** [Libresonic/libresonic#389]
Since upgrading to 6.2, I'm unable to use the DSub Android client. (Browsing is OK, but no playback/download at all, many "Connection reset by peer" errors). Since it was working fine with the 6.1 version and that the old official Android client is still working, I'm inclined to say this is related to the new version, but maybe this is my config, who knows.

Here the log file
[libresonic_6_2_dsub_5_3_5.txt](https://github.com/Libresonic/libresonic/files/984109/libresonic_6_2_dsub_5_3_5.txt)

**Comment by jooola** [comment]
Maybe same for me : 
Debian 8
OpenJDK 8
6.2 Running stand-alone
Behind HAproxy

I'm using Dsub and Audinaut.
I can download/play the songs but still i have similar logs .

Those logs appear almost randomly ( to be confirmed ) : 
When I start to download a new song while an other haven't finished yet.

Here is a sample (sorry, french logs) :
[libresonic-v6.2_logs_issue389.txt](https://github.com/Libresonic/libresonic/files/984620/libresonic-v6.2_logs_issue389.txt)

**Comment by shagr4th** [comment]
Hey, thanks for help ! but it was, as usual, PEBCAK :)
my DSub app was suddenly misbehaving and wasn't able to access /storage (hence the download error)
Like you said, those errors are still here, it seems the client close abruptly one or several requests without waiting for the server ack

I'm closing the issue since it's not a bug by itself

**Comment by jooola** [comment]
Why not leaving this open to fix it ? It maybe not a issue but could be fixed ?

( I don't like having WARN logs even if this isn't an issue )

**Comment by shagr4th** [comment]
This is also occuring with a simple GET from any http client. I'll try to debug it (want to to some dev on this project since a while) and open another one if something shows up
