### ISSUE TITLE
Chromecast is not working

### ISSUE THREAD

**Issue by Tapchicoma** [Libresonic/libresonic#390]
After updating to 6.2 I've checked if chromecast now working, but it is not.

I can start casting session, but streaming itself fails.

From chrome dev tools I see that chrome session is successfully started, but failed to load stream url:
`code: "session_error", description: "LOAD_FAILED"`

I've checked stream url and it is valid (at least browser opens it and plays song).

My suspicion is that this stream url doesn't allow other then current browser to access it and casting device so can't open it.

**Comment by Tapchicoma** [comment]
After reverting commit f7bd43136b6275 casting is working again.

**Comment by muff1nman** [comment]
Sounds like we are sending the plain stream url to the chromecast. We need to send one with the jwt token. I have a chromecast, but the earliest I can get to fixing it is this weekend.

**Comment by muff1nman** [comment]
It should now work with audio. Video may still be broken and need some work.

**Comment by Tapchicoma** [comment]
Checked, now it works perfectly. Would be nice to have something like 6.2.1 release with this bug fix included.
