### ISSUE TITLE
Fix mixed content

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#391]
[ Low priority ]

This is not a bug, but i think its better to fix this little issue.

Using : 
Libresonic 6.2 stand-alone
Debian 8
Open JDK 8
Behind HAproxy

Libresonic is working fine but i don't have the clean green lock in Firefox since they still are some mixed content : 

![capture d ecran de 2017-05-08 21-47-03](https://cloud.githubusercontent.com/assets/19195485/25822240/36fe91ca-3438-11e7-8efa-80449fb3ab89.png)

https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content

I don't know where this come from but maybe something is hardcoded ?

**Comment by muff1nman** [comment]
Your proxy is not setup correctly. See PROXY.md

**Comment by jooola** [comment]
My bad, really sorry didn't !
