### ISSUE TITLE
Database Migration (Windows)

### ISSUE THREAD

**Issue by dvoijen** [Libresonic/libresonic#392]
Hi,

I installed Libresonic on a Windwos Server with tomcat.
i would like to migrate the database to MariaDB but i need some help.
Can anyone help me trough the process?

**Comment by jooola** [comment]
I suggest you to use the IRC channel to have direct help, using issue tickets on github isn't the right thing to do.

And first use the wiki : [Here](https://github.com/Libresonic/libresonic/blob/stable/documentation/DATABASE.md)

**Comment by jooola** [comment]
Sorry i made a mistake: you should better use the embed option for the database !

Use the libresonic setting page for databas eto set it up it will be easier

**Comment by dvoijen** [comment]
Joola i figured it out...
My settings are:

```
DatabaseMysqlMaxlength=512
DatabaseConfigType=EMBED
DatabaseConfigEmbedDriver=org.mariadb.jdbc.Driver
DatabaseConfigEmbedPassword=<PASS>
DatabaseConfigEmbedUrl=jdbc:mysql://localhost/libresonic?sessionVariables=sql_mode=ANSI_QUOTES
DatabaseConfigEmbedUsername=libresonic
DatabaseUsertableQuote=
```

In the "C:\Program Files (x86)\Apache Software Foundation\Tomcat 8.5\lib" i downloaded: mariadb-java-client-1.5.9.jar

**Comment by jooola** [comment]
Great, could you close the issue now ?
