### ISSUE TITLE
Migrate datas

### ISSUE THREAD

**Issue by dorel14** [Libresonic/libresonic#393]
Hello as said in another issue i plan to migrate my datas to another database , i try to connect to libresonic db with talend but i don't know the login and password to connect , where can i find it .

THX

**Comment by jooola** [comment]
DB name, DB user and DB passwd are those you used when you created the external database.

You need to create the external database before connecting libresonic to it.

And again i'm not a DB o just trying to help :p

**Comment by fxthomas** [comment]
I am unfortunately not familiar with Talend, but I wrote some tips about `sqltool` [here](https://wiki.archlinux.org/index.php/Subsonic#Accessing_the_database) a while ago, this should still work with Libresonic.

**Comment by dorel14** [comment]
Thx i have seen the db user to log in hfsql db , i can now export it in csv or other in Talend , i ll work on a talend job to migrate to mysql.
