### ISSUE TITLE
Find new fonts and provide them locally

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#398]
I think we should provide fonts locally instead of loading them from the google api

**Comment by fxthomas** [comment]
Previous discussion in #173! :)

**Comment by jooola** [comment]
Oh my bad, still can't we re discuss this ?
I see that you're PR was more about storing them locally. After reading it we could discuss which fonts we could use so we can store them locally.
I mean we could change the fonts to fit the GPLv3 license.

**Comment by fxthomas** [comment]
Definitely! The only issue is with the Ubuntu font (which is as far as I can tell only used in headers), why not replace everything with Roboto?

**Comment by jooola** [comment]
I think that we could unify the fonts on all page and add a way to select which font you wanna use.
Open Sans and Roboto are pretty much similar but we could look for some other fonts !

Well added a setting to change the font is not really a high priority ( could be useless ) but i think storing them locally has to be done.

**Comment by jooola** [comment]
This is with Open Sans fonts

![image](https://cloud.githubusercontent.com/assets/19195485/26287872/52ea8208-3e84-11e7-9f19-066635ea1c32.png)

**Comment by jooola** [comment]
Using only one font should speed up the loading. No need to load Roboto and Ubuntu...

**Comment by jooola** [comment]
Open Sans:
![opensans_font](https://cloud.githubusercontent.com/assets/19195485/26504850/9fdce1e4-4246-11e7-806d-c97ad0bbdeaa.png)

Roboto:
![roboto_font](https://cloud.githubusercontent.com/assets/19195485/26504851/9ffce1ce-4246-11e7-87f1-884c6ae6f72b.png)
