### ISSUE TITLE
Player objects are not cached

### ISSUE THREAD

**Issue by biconou** [Libresonic/libresonic#401]
In Libresonic, Player domain object are not cached. hence, each time we need to get Player informations the org.libresonic.player.dao.PlayerDao#getPlayerById method if invoqued fireing a new sql query. That's a mess. 
org.libresonic.player.dao.PlayerDao#getPlayerById is invoqued very very often especially by services like NowPlayingService, Jukebox rest service etc ...
Another downside is that, for the new java jukebox player, I'd like to keep a reference to the audio player into the Player object Instance.

Are you ok if I create a cache (preferably using ehcache) for the Player objects ? 
Of course cached objects will be renew in case one change the player configuration.

**Comment by muff1nman** [comment]
I would say this is not worth our time. The database query is going to be pretty fast because that table is quite small. I doubt adding a cache would help in a meaningful way.

**Comment by jooola** [comment]
Why not keep this open for the future ?

**Comment by biconou** [comment]
@muff1nman Even if the query is fast, I think it is bad thing to run the same query over the database every 10 seconds (must be multiplied by the number of active players).
I already coded main of this las night. I could submit a PR.

**Comment by muff1nman** [comment]
I don't see any value in it and would not merge it. Rather we need to fix up the source of the problem, the ui.

**Comment by biconou** [comment]
As you like.
