### ISSUE TITLE
Rebase onto new history

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#41]
The current "release" branch is based upon SVN-imported history and contains Subsonic-related artifacts(eg, the subsonic.org website) that are not part of the Subsonic software. https://github.com/sindremehus/subsonic is a "dumb import" of the 5.3 codebase, and is free of these artifacts.

This ticket will cover the process of rebasing Libresonic-specific changes onto the new git history.

**Comment by EugeneKay** [comment]
I have pushed the new git history as develop, which is an orphan(unconnected) branch. All other branches and tags have been removed. You should re-clone your local repository and force-push or re-clone any Github forks. I created Libresonic/subsonic-svn and pushed the old history and tags there for archival.

I rebased-out the 6.0-beta1 merge and related changes, rolling back to 5.3. A direct-rebase against the new history failed(because of the orphan branch and the difference in line-endings between the two histories). Instead, I copied the current state into develop, and committed the result. This loses authorship history, but this is worth the saved trouble.

**Comment by slang800** [comment]
Aww... now the git log is cleared and we can't see the history of the code :(

**Comment by EugeneKay** [comment]
Per my last comment, the old history was pushed to https://github.com/Libresonic/subsonic-svn for archival. You can reference it there if necessary.
