### ISSUE TITLE
Storage of Song ratings

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#415]
Consider storing song ratings inside id3 tags. This was requested by nickloddin on IRC.

**Comment by muff1nman** [comment]
```
15:55:24muff1nmanso rather than replacing the existing mechanism
15:55:32muff1nman i could see it more being a switch
15:55:47muff1nman that only affects the user_rating table
15:56:08muff1nman i.e. choice between database and id3 for song ratings only
```

**Comment by codicusmaximus** [comment]
I don't think it would be a good idea to store ratings in the tags.  This would be ratings and other metadata for multiple users, IMO alternate file/data streams are perfect for this kind of data storage
In the windows world, ADS: https://en.wikipedia.org/wiki/NTFS#Alternate_data_streams_.28ADS.29
In *nix they're called EA (extended attributes)

**Comment by codicusmaximus** [comment]
Why was this closed?  And what is airsonic?  Is there something going on to this project?
