### ISSUE TITLE
New login layout

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#416]
This issue is a discuss about some changes on the login page.
PR is almost ready but maybe some things needs to be discussed !

Original : 
![image](https://cloud.githubusercontent.com/assets/19195485/26228040/92618d96-3c36-11e7-83a3-445dd56cdd9d.png)

Here is a screenshot with the changes

![image](https://cloud.githubusercontent.com/assets/19195485/26226521/dcd764d6-3c2c-11e7-9c91-1f2a44eb22d3.png)

**Comment by jooola** [comment]
Here is screen with the logo centered only : 
![image](https://cloud.githubusercontent.com/assets/19195485/26229165/e2dc55cc-3c3f-11e7-8e6f-4a36f180d9a1.png)

**Comment by jolny** [comment]
The first one with changes makes more sense, imo. The design is more clean overall. But make the button the same width as the text fields :)

**Comment by jolny** [comment]
Same size is fine, but on the first picture the button was ~10 pixels smaller than the Username and Password fields :)
Another Color might work great! Blue would probably be a good choice considering the logo etc.

**Comment by jooola** [comment]
![libresonic_login](https://cloud.githubusercontent.com/assets/19195485/26279824/6457c5a8-3dbe-11e7-9365-341e8fe82be0.gif)

**Comment by jolny** [comment]
Weird!
Looks good though, I like it :)

**Comment by jooola** [comment]
![image](https://cloud.githubusercontent.com/assets/19195485/26287528/ce0e77c0-3e7d-11e7-8a23-ab45e49ead4a.png)

**Comment by jooola** [comment]
![image](https://cloud.githubusercontent.com/assets/19195485/26287592/333b6a44-3e7f-11e7-9aa9-1d93f028a437.png)

**Comment by SuperNerd-James** [comment]
I quite like the last GMail login page, where you type your username and it then loads your avatar. Could we do that with this, or is there a lot of code involved?

**Comment by jooola** [comment]
You mean that the login will need 2 frames 1 for the username and another for the password ?
And sliding from one to another ?
I don't think that we really need to have a high tech new login page and i'm not into adding too much code !
Not everyone is using avatar too , and i would like to remove avatars too ! :p

**Comment by SuperNerd-James** [comment]
No, the username and password fields will be both present and static. As soon as the user enters their username and hits Tab or clicks out of the box into the pass field, the system does a lookup in the DB for the user, and loads their avatar if set.

I like avatars, they're identity, but then I guess it's subjective :)

**Comment by jooola** [comment]
I think this is too much work code to add ! Avatar lookup, security... I won't build this.
I'm more looking for faster solutions than adding tons of code.

**Comment by biconou** [comment]
I think that, for security reasons, it is not a good practice to give a clue that a user name actually exists before being authenticated.

**Comment by jooola** [comment]
Yup right, closing this since we merged #431
