### ISSUE TITLE
External streaming does not work

### ISSUE THREAD

**Issue by gerroon** [Libresonic/libresonic#419]
@muff1nman 

The streaming via "external player with playlist" does not seem to work at all ;( All the players I tried (vlc, smplayer, mpv) have problem playing any of the songs. The weird thing is that they cant play from the actual Libresonic's non proxy urls that runs on :8080

Here is a log from mpv trying to stream from actual Libresonic server (non Apache proxy)

    mpv "http://192.168.xx.xx:8080/libresonic/stream?player=9&id=89299&suffix=.mp3"
    Playing: http://192.168.xx.xx:8080/libresonic/stream?player=9&id=89299&suffix=.mp3
    [ytdl_hook] ERROR: Unsupported URL: http://192.168.2.133:8080/libresonic/login
    [ytdl_hook] youtube-dl failed, trying to play URL directly ... 
    Failed to recognize file format.

    Exiting... (Errors when loading file)

This issue seems to be consistent with Apache Proxy and Libresonic's internal server streaming

**Comment by muff1nman** [comment]
I think this might be more fallout from #328 . Sorry bout that.

**Comment by gerroon** [comment]
Here some logs

http://pasteall.org/40364http://pasteall.org/4036499

I did not realize that Dsub was streaming at the same time (so you see normal streaming lines) but I tried playing play external urls with players which I believe generated some errors. Hopefully they are here in the log.

**Comment by muff1nman** [comment]
The giveway is mention of the login url. It's being redirected to the login page as it doesn't have access.

**Comment by gerroon** [comment]
Thanks for the follow up.

**Comment by muff1nman** [comment]
This is actually still not working after doing further tests today. Will fix.

**Comment by muff1nman** [comment]
Verified to work with vlc.
