### ISSUE TITLE
Change major usages of "Subsonic"

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#42]
The major usages of "Subsonic" should be changed to "Libresonic" in the user-facing portions of the application. This will reduce confusion associated with the Fork for new versions.

This issue is used to track finding and patching these changes. Please create a Pull Request and reference this Issue. If you have a comment, you can leave it here(refrain from commenting "Me too!", etc).

**Comment by csobsidian** [comment]
As a note, I've started going through and finding these items. Obviously, they are quite numerous, but some are not as clear cut as they might seem. For instance, there are references to "Subsonic Premium" which have no context here. I think it would be wise to not touch any items that may be later slated for removal. That will make them easier to find. Thoughts?

**Comment by EugeneKay** [comment]
I agree; let's leave "Subsonic Premium" references alone. Removing those(and squashing the remnants of the licensing code) are best left handled in a separate Issue further down the line.

Mostly, I want to make it clear that Libresonic is not the same software as Subsonic.

**Comment by csobsidian** [comment]
Okay. I actually had some time today and am working through these now with the rebased code. A couple of more notes on things I am not changing at this time:

- Copyright notices that contain info about Subsonic. A new issue should be started (and dedicated) to tackling these.

- the getBrand() function of the SettingsService as I do not know how this will affect other operations.

**Comment by csobsidian** [comment]
There are also a large number of references to subsonic website addresses in the localization files.

**Comment by csobsidian** [comment]
Subsonic logos exist in the webapp for each theme (i.e. [logo.png](https://github.com/Libresonic/libresonic/blob/develop/subsonic-main/src/main/webapp/icons/buuftheme/logo.png)) and there is also a large format logo: [subsonic-512.png](https://github.com/Libresonic/libresonic/blob/develop/subsonic-main/src/main/resources/net/sourceforge/subsonic/service/subsonic-512.png).

**Comment by csobsidian** [comment]
Do we want to put in a placeholder logo for these images until issue #43 is resolved and we have a new logo?

**Comment by EugeneKay** [comment]
Merged #59.
