### ISSUE TITLE
Transcoding with avconv: Permission denied

### ISSUE THREAD

**Issue by juanghurtado** [Libresonic/libresonic#423]
Hi there!

First of all: great work with Libresonic! It's amazing!

I have a Libresonic WAR on Tomcat8 running as a service on Raspbian Jessie. Since this OS version has deprecated `ffmpeg`, I need to use `avconv` instead. I have setup the `avconv` command on the settings page of Libresonic (`avconv -i %s -b %bk -q 0 -loglevel error -f mp3 –`) and created a symbolic link to the `avconv` binary into `/var/libresonic/transcode/avconv`, but I keep getting permission errors:

```
2017-05-19 14:25:50.502  INFO --- o.l.p.io.InputStreamReaderThread         : (/var/libresonic/transcode/avconv) –: Permission denied
```

Tomcat8 is running as a service through the `tomcat` user.  The symbolic link is owned by that `tomcat` user. In fact, if I do `sudo -u tomcat /var/libresonic/transcode/avconv` the command responds successfully.

What could be happening? How does Libresonic use the transcoding command? I guess that it should be as a system command through the user running the WAR, but… well… permissions error as you see…

Do you have any idea?

Thanks a lot.

**Comment by jooola** [comment]
Hi,
What are the permissions of the avconv binary ?
Does jessie-backports exist on raspbian ? Because ffmpeg is available in the jessie-backoprts from debian jessie.

Did you try to replace avconv with a ffmpeg binary ?

**Comment by juanghurtado** [comment]
Both (symbolic link and binary) have full permissions (as a last resort):

```
$ ls -la /var/libresonic/transcode
lrwxrwxrwx 1 tomcat tomcat   15 May 19 21:55 avconv -> /usr/bin/avconv

$ ls -la /usr/bin | grep avconv
-rwxrwxrwx  1 root root     133632 Apr 26 09:26 avconv
```

I've tried to `chown` the binary to the `tomcat` user, but everything stays the same.

The user is `tomcat`, I made the Tomcat setup myself, not through `apt-get`. In fact, `ps aux | grep java` shows that the Libresonic instance is being run by `tomcat` user:

```
tomcat   15547 28.4 28.1 712880 266832 ?       Sl   21:55   2:14 /usr/lib/jvm/java-8-oracle/bin/java -Djava.util.logging.config.file=/opt/tomcat-latest/conf/logging.properties -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Dfile.encoding=UTF-8 -Dnet.sf.ehcache.skipUpdateCheck=true -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+UseParNewGC -XX:MaxPermSize=128m -Xms512m -Xmx512m -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -classpath /opt/tomcat-latest/bin/bootstrap.jar:/opt/tomcat-latest/bin/tomcat-juli.jar -Dcatalina.base=/opt/tomcat-latest -Dcatalina.home=/opt/tomcat-latest -Djava.io.tmpdir=/opt/tomcat-latest/temp org.apache.catalina.startup.Bootstrap start
```

If I can't get `avconv` working, I'll try with `ffmpeg` from jessie backports, but that is my last resort. I'd prefer to understand what is happening first.

Thanks a lot for your response.

**Comment by jooola** [comment]
Reading [THIS](https://github.com/Libresonic/documentation/pull/3) avconv and ffmpeg works the same.
So you could try to create a ffmpeg link to avconv :
```
ffmpeg -> /usr/bin/avconv
```

**Comment by juanghurtado** [comment]
I ended up installing `ffmpeg` from jessie backports. Still don't get why the permission issues with `avconv`. Anyways, closing issue. Thanks!
