### ISSUE TITLE
admin user lost settings option in menu

### ISSUE THREAD

**Issue by antipiot** [Libresonic/libresonic#424]
hi!
I've spotted a strange thing when i wanted to setup something on my libresonic server: 
My main accout, admin, lost the settings menu in the web UI.

To get access back i reached the settings page from: http://libresonic/settings, created a new user with admin rights then logged with this user and the settings menu appeard correctly. i remember having access to this menu after updating to 6.2. strange thing.

Anybody else?

**Comment by jooola** [comment]
What's your configuration ?

**Comment by antipiot** [comment]
i'm actually using the lastest docker from linuxserver.io

Version	6.2 – May 19, 2017
Server	jetty/9.3.14.v20161028, java 1.8.0_121, Linux (473.0 MB / 832.0 MB)

**Comment by jooola** [comment]
Fixed ?

**Comment by antipiot** [comment]
Yup, i did a new clean install and everything is ok. think something went wrong when i updated to 6.2

Sorry, i'm note used to Git :-)

**Comment by izderadicka** [comment]
Same issue here after migrating to  release 6.2  – May 2, 2017 a time ago (from some 6.2 beta).  Admin lost Setting menu item in main bar. Also cannot switch players.   Setting page can be accessed by direct link - however Player | Personal | Shared media setting have 403 access denied error
