### ISSUE TITLE
Create a new Logo

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#43]
A new logo is required for Libresonic. I do not have any art sklls, so community input is required. Please place your submission in the comments and I will arbitrarily pick the best one at an indeterminate future time. Please use GIthub's "reactions" emoji to vote; comments without a submission will be pruned.

**Comment by williamkray** [comment]
![ls1](https://cloud.githubusercontent.com/assets/8409433/15064842/cb657560-130d-11e6-8c1d-463ffd5028df.png)

it's not amazing, but it's a start. Blue == freedom, L == libre, and soundwaves coming from a... speaker? cone? it'll get the ball rolling. trying to keep it clean, flat, and simple per current design trends.

**Comment by williamkray** [comment]
![ls2](https://cloud.githubusercontent.com/assets/8409433/15065458/b4be0168-1314-11e6-8456-793a8c22b398.png)

variation with negative space. but i think this is getting too busy.

**Comment by jolny** [comment]
I'm not a designer so I won't torment you with my paint skills. I just have a suggestion since I'm a bit punny. The german word "Lieber" means dear/beloved, etc. so maybe the new logo could contain a heart? Hearts also have round shapes, which would go well with soundwaves etc.
I like your second logo better @williamkray , I like the idea of blue and white together. Also, It's more "icon shaped" than the first one.

**Comment by csobsidian** [comment]
I am proposing the use of the two following logos for the time being until this issue can be fully resolved.
![logo-large](https://cloud.githubusercontent.com/assets/8325573/15113675/58de20c2-15bb-11e6-9fc6-47b310d92b5d.png)
![logo-smallwide](https://cloud.githubusercontent.com/assets/8325573/15113676/58dfdaf2-15bb-11e6-924e-f27b2f0d49ae.png)

The small icon is used as a placeholder for the small format logo used by themes. Besides, who doesn't love scriptina?

**Comment by jooola** [comment]
i Like William cray logo ! maybe merge it too ?

**Comment by csobsidian** [comment]
Iterating on @williamkray's layout and color scheme. Let's keep this moving with ideas!
![logo-large](https://cloud.githubusercontent.com/assets/8325573/15147320/b87c808a-1685-11e6-83f0-580f76814521.png)
![logo-large2](https://cloud.githubusercontent.com/assets/8325573/15147324/bf28dc4e-1685-11e6-989f-74cf963f22c3.png)
![logo-large3](https://cloud.githubusercontent.com/assets/8325573/15147329/c407d756-1685-11e6-8b95-c9e357464689.png)

**Comment by EugeneKay** [comment]
583d45a was merged in #59 which included a temporary logo from @csobsidian. That is good enough for the 6.0 release, but I don't like it for the long-term. My personal preference is for @williamkray's first design, which looks good on a generic white/transparent background. The radiating soundwaves imagery is nice. I'm moving this Issue to Future, and will check back in 1-2 weeks to make a decision. Please, keep the logos coming!

**Comment by williamkray** [comment]
thanks for the feedback! i've taken it in, and re-configured the original icon, as well as threw together a text-style icon that can be used in conjunction. for the sake of not making this thread go on forever and ever, i'll post one of each here, and a link to the full files (with examples of the logo on top of various colored backgrounds). those can be found here: https://www.kray.ca/owncloud/index.php/s/gwaKO5Lede4muEZ

the font used is Comfortaa, which uses the SIL Open Font License v1.10. it's available from fontsquirrel here: https://www.fontsquirrel.com/fonts/Comfortaa

![text1](https://cloud.githubusercontent.com/assets/8409433/15270881/6df15d94-19e4-11e6-9285-f376c22941cf.png)
![ls5_grey](https://cloud.githubusercontent.com/assets/8409433/15270882/6df4bfc0-19e4-11e6-89dd-1b35ba010fed.png)

**Comment by ttsda** [comment]
What about something like this?

![logo](http://i.imgur.com/IFmFl0b.png)

**Comment by EugeneKay** [comment]
This did not make it into the 6.1 release due to a lack of PR. It looks like @ttsda's submission has the most thumbs-up right now.

**Comment by ttsda** [comment]
I'll have to look for the original files but I can provide them if you decide to use mine :) Thanks

**Comment by EugeneKay** [comment]
@ttsda A Pull-Request would be awesome. You can reference 583d45a for the files that need to be replaced. I can do it myself with the originals. but it'll have to wait until the weekend.

**Comment by EugeneKay** [comment]
@ttsda Any sight of the originals ?

**Comment by ttsda** [comment]
@EugeneKay Please check the PR :)
