### ISSUE TITLE
Move to Semantic Versioning

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#44]
Presently, the Subsonic-5.3-KANG binaries prompt the user to upgrade to Subsonic 6.0. We need to bump our version to match to address these.

The update-checker code must be located, and patched to look at a LIbresonic version instead of Subsonic. I have not had a chance to do this yet. Can somebody can look into the implications and possibly create a Pull Request?

**Comment by csobsidian** [comment]
I don't currently have a system setup with the proper tool chain but here's what I've found:

The [Version Service](https://github.com/Libresonic/libresonic/blob/release/subsonic-main/src/main/java/net/sourceforge/subsonic/service/VersionService.java) has an embedded URL for pulling the most recent version info.
`private static final String VERSION_URL = "http://subsonic.org/backend/version.view";`

This page currently returns the following information:

```
SUBSONIC_VERSION_BEGIN6.0SUBSONIC_VERSION_END
SUBSONIC_FULL_VERSION_BEGIN6.0SUBSONIC_FULL_VERSION_END
SUBSONIC_BETA_VERSION_BEGIN6.0.beta2SUBSONIC_BETA_VERSION_END
```

This information is then compared to a version string stored in a text file at ./WEB-INF/classes/version.txt. That local text file is created from the [POM.xml](https://github.com/Libresonic/libresonic/blob/7456fc4a430c3ab8a77ee5a0298b2c9ba7017ce6/subsonic-main/pom.xml) at build time and contains the current project version:

```
<parent>
  <groupId>net.sourceforge.subsonic</groupId>
  <artifactId>subsonic</artifactId>
  <version>6.0.beta1</version>
</parent>
```

Callers to the version service such as the [Right Controller](https://github.com/Libresonic/libresonic/blob/release/subsonic-main/src/main/java/net/sourceforge/subsonic/controller/RightController.java) use this information to setup the proper view.

```
if (userSettings.isFinalVersionNotificationEnabled() && versionService.isNewFinalVersionAvailable() {
  map.put("newVersionAvailable", true);
  map.put("latestVersion", versionService.getLatestFinalVersion());
} else if (userSettings.isBetaVersionNotificationEnabled() && versionService.isNewBetaVersionAvailable()) {
  map.put("newVersionAvailable", true);
  map.put("latestVersion", versionService.getLatestBetaVersion());
}
```

For the near term the implications appear to be as simple as redirecting the version service to a new URL maintained by Libresonic. Long term this is wrapped into the re-branding and move away from the subsonic namespace.

**Comment by EugeneKay** [comment]
ba28695 changes the VersionService URL to use libresonic.org. I have placed a plaintext file at the appropriate location and listed 5.3 as the current version.

**Comment by csobsidian** [comment]
cross domain policy maybe?

**Comment by csobsidian** [comment]
[2016-05-09 13:06:18,052] WARN VersionService - Failed to resolve latest Subsonic version.
javax.net.ssl.SSLException: hostname in certificate didn't match: <libresonic.org> != <*.kashpureff.org> OR <*.kashpureff.org> OR <kashpureff.org> OR <www.kashpureff.org>
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:227)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:147)
...

**Comment by EugeneKay** [comment]
That means that this is a ServerNameIndication issue in Libresonic or the Java stdlib..... Ugh. A quick search yields https://issues.apache.org/jira/browse/HTTPCLIENT-1119 among others.

**Comment by EugeneKay** [comment]
@zifnab06 volunteered to look at this.

**Comment by EugeneKay** [comment]
I have bumped the version numbers(dc2d450). I have decided to revert to using a HTTP URL for now(b90eb07) and opened #74 for a future release.
