### ISSUE TITLE
Support the new startScan endpoint

### ISSUE THREAD

**Issue by mshick** [Libresonic/libresonic#442]
In version 6.1 / API version 1.15 Subsonic added the `startScan` endpoint: http://www.subsonic.org/pages/inc/api/examples/scanStatus_example_1.xml

It would be great to see this supported, perhaps along with the `getScanStatus` endpoint for feature parity.

I added an issue #439 discussing a use-case I have for this — triggering scans on library updates determined via external routines.

**Comment by muff1nman** [comment]
Yes this definitely something we should add. With that said, we may need to also consider what the longer term picture is for our API endpoint while dealing with adding this. Does it make sense to do a full on upgrade to the 1.15 API? Or just take pieces and parts and modify to our taste. Perhaps it makes sense to keep the subsonic api as is and separate out a new [versioned](https://www.troyhunt.com/your-api-versioning-is-wrong-which-is/) libresonic api for things that are unique to libresonic. What about for the things we dont support within the subsonic api like the chat feature? Perhaps a [410 http return code ](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.11) would be more appropriate then returning 404s.

I had made the change to distinguish the rest api in #329 which is currently only in the develop branch, but I'm wondering if that was a bad idea as its confusing as to what subsonic api version libresonic is compatible with. Perhaps that change needs to be reverted.

Curious on the thoughts of our mobile friends, @nvllsvm and @daneren2005

**Comment by nvllsvm** [comment]
Since this is a brand-new feature added in an API version more recent than Libresonic's, adding it should be of no consequence. Though unless we plan on supporting all of API 1.15's features, Libresonic should continue advertising the version it current is at.

In the grander scheme of things, we should evaluate creating a new API exclusive to Libresonic even if it's limited to admin functions such as this. I would eventually like to see the Libresonic server decoupled entirely from the UI with communication between the two happening over an HTTP API.

**Comment by daneren2005** [comment]
For features which are not supported in Libresonic at all, if you could create a list of them it would be simple to check for a Libresonic server and limit what options are shown for those users.  I agree that we should get a full feature set for v1.15 before claiming to support it though.

While Libresonic will probably need to split off it's own version of the API, from a user's stand point it would be better so maintain a Subsonic compliant API as well.  The number of apps which will be maintaining support for Libresonic will always be smaller than those which support the standard Subsonic API.  There is healthy competition on, say, Android.  But on iOS for example I don't think any of the apps are even targeting Madsonic yet which probably has a much larger userbase than Libresonic does.

**Comment by muff1nman** [comment]
What is the current method of checking for a libresonic server? Is #329 not needed?

In general it sounds like the consensus is to not modify the subsonic API and to upgrade when we can. A Libresonic specific API can be separate.

**Comment by daneren2005** [comment]
I thought #329 was already in.  So I guess I should say that in the *future* it will be easy to tell which severs are Libresonic ones.

**Comment by muff1nman** [comment]
Well it's in the develop branch, but I don't really consider anything finalized till it's in stable ;)

**Comment by muff1nman** [comment]
Resolved in #461
