### ISSUE TITLE
last.fm scrobbling for all players? [already does this is the player supports it]

### ISSUE THREAD

**Issue by chrisbeckstrom** [Libresonic/libresonic#445]
Love libresonic, thanks for your hard work!

I especially love the Last.fm integration. However, it appears to only be scrobbling plays in the browser; I'm also playing tracks using the iOS client "supersonic" and those are not being recorded in Last.fm.

I would love if all plays in any player were scrobbled. 
Is this possible?

here's my version info:
```
Version	6.2 – May 2, 2017
Server	Apache Tomcat/8.5.11, java 1.8.0_131, Linux (644.3 MB / 837.0 MB)
```

**Comment by muff1nman** [comment]
Dsub I believe does this, but really this might be a better question aimed at the supersonic folks. We have the API to do it, it should just be a matter of your client correctly hitting that endpoint.

**Comment by chrisbeckstrom** [comment]
Ah, thanks! I was thinking the scrobbling was done from the server, but it sounds like it's actually done from the client. Makes sense, thanks

**Comment by muff1nman** [comment]
Well it is done from the server if the client calls our api to do so. We then scrobble to lastfm on behalf of the client.

**Comment by chrisbeckstrom** [comment]
Thanks for clarifying! I've tried out a few different iOS apps and some of them seem to be scrobbling fine. Some don't actually playback music, which of course is a whole different issue. Thanks for your help! I'll close this out.
