### ISSUE TITLE
Mediaelement.js Placeholder issue

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#448]
This issue is to track the larger progress on mediaelment.js migration effort. So far we have the basics in place from #425. The updated checklist of remaining items is as follows:

#### PR Merged
- [x] Liquibase changes reverted
- [x] New Liquibase migration for any new transcodings we want/need to use with mediaelement to at least get it working OR see if `video/flv` works
- [X] steps for reproducing the mediaelement sources (i.e. in case of upgrade)

#### Develop Merged to Stable
- [ ] ~Remove duplicate code between audio and video `CastPlayer`s~ EDIT: descoped
- [ ] ~Move `CastPlayer` javascript embedded in videoPlayer/playQueue.jsp to standalone js~ EDIT: descoped
- [ ] ~Chrome cast support (use mediaelement plugin)~ EDIT: descoped
- [ ] Full screen control OR use ME controls for video (although I'd like to see this one done as part of the PR, it might be dependent on some of these other tasks)
- [ ] Stylizing of ME to match themes (#457)
- [ ] Update external player to use ME
- [ ] Remove jwplayer sources

#### Future work
- [ ] Support no transcode in the case none is needed.
- [ ] Change format type to use accept header (allows proper negotiation with server without a statically set format)
- [ ] Research into the most optimal video formats to use and prioritize them.

**Comment by muff1nman** [comment]
@Eusmilis I took a crack at the css to at least make it look somewhat like ME fits in. Let me know if it looks like trash or if you have any suggestions (I haven't done css in a while :)

**Comment by muff1nman** [comment]
@Eusmilis any luck on trying out the builtin chromecast support for mediaelement?

**Comment by Eusmilis** [comment]
I made some progress, but I didn't have much time lately.

I changed the security config to remove the need for a jwt token, but the chromecast plugin for MediaElement still doesn't work. When I switch to chromecast, it casts about 1 second and stops.

However, after fixing the source for `cast_sender.js` the video `CastPlayer` works fine.

**Comment by muff1nman** [comment]
Okay so perhaps it's not worth the effort to move the casting implementation? Also feel free to submit a PR to fix the source for cast_sender.js.

**Comment by Eusmilis** [comment]
Since making the plugin work would require a lot of work and wouldn't be enough to get rid of the current UI (Using the MediaElement video player, the progress bar only show what has been buffered), I don't think it is worth it for now.

I still have to add a security token to the stream url before submitting a PR.

**Comment by muff1nman** [comment]
Sounds good, I've updated the top level comment to reflect that. To clarify on the PR for fixing cast_sender.js, you're saying we would need to add the token for the stream url we send to the chrome cast as 1ec32f28ca574772402f304a1de39cb6255aea98 isn't sufficient for the recent changes for MediaElement?

**Comment by Eusmilis** [comment]
Yes, 1ec32f2 adds the token to the audio stream urls in the playqueue, but the video stream url doesn't have it.
