### ISSUE TITLE
Evaluate other Forks

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#46]
Other Forks of Subsonic exist, many of which add new features. Most of them are unmaintained. What are the options out there and their current status?

**Comment by slang800** [comment]
First few I've found:

- [FutureSonic](https://github.com/FutureSonic/FutureSonic-Server)
- [supysonic](https://github.com/spl0k/supysonic) (Python reimplementation)
- [madsonic](http://madsonic.org/)
- [Iposonic](https://github.com/ioggstream/iposonic) (Python reimplementation)

**Comment by csobsidian** [comment]
I'm curious as to the purpose of this issue. Are we looking at good features from other forks that we would like to roll in as enhancements to the Libresonic codebase?

**Comment by EugeneKay** [comment]
Integrating other forks was suggested. I am open to the idea of cherry-picking enhancements, but they need to be examined and vetted first. This Issue does not have a well-defined purpose just yet because I don't know what the landscape looks like. ;-)

**Comment by apastuszak** [comment]
Madsonic is GPL 3 licensed.

It has an HTML5 player.

**Comment by slang800** [comment]
found another: https://github.com/Mach5/supersonic ... "Open-source web-based media streamer and jukebox fork of Subsonic"

**Comment by kornkid5622** [comment]
Madsonic also has support Split value tags (genre specifically) this would be an excellent feature to add as currently in Subsonic my genre list looks like this: http://i.imgur.com/NMRXzsS.png while in madsonic it looks like this: http://i.imgur.com/bKhoraV.png this is the main reason i've been using madsonic over subsonic recently.

**Comment by TheFlatworm** [comment]
I really liked Musiccabinet. http://dilerium.se/musiccabinet/.  It seemed like code was really cleaned up and used a different database.
