### ISSUE TITLE
Add second admin to Libresonic repository ?

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#464]
This issue is ticket to add a second admin to the Libresonic repo.

@EugeneKay you're not working a lot with us and you're rarely here, so I suggest to add a second admin to the repo.
Maybe @muff1nman ? Currently you is the one managing Libresonic.

The main problem is that some issue needs the permissions of an admin to be solved.
Here for example is a ticket unsolved, everything is ready but we can't get this closed.
See by yourself : #100

**Comment by EugeneKay** [comment]
Github Issues is not the appropriate place to have this discussion. Feel free to poke me on IRC, but my responses are delayed due to real life.
