### ISSUE TITLE
New Website

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#47]
Need a new website !
I will get some topics from other website and build a large wiki !
I may need some help !
enhancement 
low priority

**Comment by EugeneKay** [comment]
For now we will use the front page for this repository. A gh-pages site would be the preferred method.

**Comment by csobsidian** [comment]
I've not used gh-pages before. Can i create the branch on my fork and then pull it as a branch into master or do you have to create the branch first?

**Comment by EugeneKay** [comment]
I have created an organization-level page at Libresonic/libresonic.github.io. Ideas are welcomed as Issues there.
