### ISSUE TITLE
TimeoutException when transcoding m4a files

### ISSUE THREAD

**Issue by arielelkin** [Libresonic/libresonic#472]
Libresonic v6.2

Libresonic plays fine any mp3 files, but can't play m4a (ALAC) files on the Web player. The player is updated with the track's duration, but playback won't start. 

Here are the logs: 

Google Chrome 58.0.3029.110
https://pastebin.com/raw/tkdip7aY

Safari 10.1.1
https://pastebin.com/raw/q1dHPYug

**Comment by biconou** [comment]
The transcoding might have crashed. It uses ffmeg with a command like this one (present in your log).
[/config/transcode/ffmpeg] [-i] [/music/Eddie Shinn & Step/The Third Is Not Superfluous/01 Happy Mondays.m4a] [-map] [0:0] [-b:a] [192k] [-v] [0] [-f] [mp3] [-]

Could you try to run this command in a shell ? 
/config/transcode/ffmpeg -i /music/Eddie Shinn & Step/The Third Is Not Superfluous/01 Happy Mondays.m4a -map 0:0 -b:a 192k -v 0 -f mp3 -

I think it won't work. You should add a new entry in the transcoding settings for this particular file type (ie m4a).

**Comment by jooola** [comment]
Maybe related to #343

**Comment by arielelkin** [comment]
@biconou @jooola  thanks for your response 🙂 

It's probably not related to the transcoding, as I'm able to play the same m4a files without a problem using [an iOS app](https://itunes.apple.com/us/app/play-sub-subsonic-music-streamer/id955329386?mt=8).

the logs read:

```
2017-06-22 01:04:32.658  INFO --- o.l.p.io.PlayQueueInputStream            : ariel listening to "The Third Is Not Superfluous/01 Happy Mondays.m4a"
```

Anyway, I've run the command you wrote, it outputs a bunch of gibberish:
https://pastebin.com/raw/Renfxq3x

Here are my transcoding settings:

![image](https://user-images.githubusercontent.com/1756909/27412825-e5d87adc-56cd-11e7-9189-c007282a975f.png)

Isn't this more of a a problem with the web player rather than with the transcoding?

**Comment by arielelkin** [comment]
Couple of updates:

* Libresonic is transcoding and streaming WAV files fine, so those transcoding settings work 
* the iOS app is able to natively read m4a ALAC, so libresonic is streaming the original m4a to it, without any transcoding. that's not the case on Chrome and Safari.

**Comment by arielelkin** [comment]
bump 🙂

**Comment by muff1nman** [comment]
I currently have some issues with m4a files on rhel buts I think it's because my ffmpeg build is lacking support for that transcoder. I've been meaning to recompile ffmpeg and then test m4a, just haven't gotten round to it yet :/

**Comment by EugeneKay** [comment]
I can confirm that CentOS' ffmpeg fails to play a m4a test file. This is not a Libresonic issue, complain to upstream.

**Comment by arielelkin** [comment]
@EugeneKay thanks for the response

Note that ffmpeg does play m4a files on Ubuntu, the OS I'm using, so the issue might not necessarily be with ffmpeg or CentOS. At any rate, I would believe that if ffmpeg had issues playing m4a files, a bug would have already been raised [on their bug tracker](https://trac.ffmpeg.org/search?q=m4a) by now, and it hasn't)

You can also do a quick verification that the issue is with Libresonic rather than the OS or the transcoder itself, by doing a quick and fresh libresonic install using this container:
https://github.com/linuxserver/docker-libresonic/

(which is also what I'm using myself)

Do you think the default transcoding settings need to be adjusted for m4a?

**Comment by EugeneKay** [comment]
That is a possibility. I do not have any M4A files myself - I had to download a test file to even verify the above.  This is something that really should be handled in unit tests, but I am being realistic. Feel free to check it out in more detail and re-submit as a transcoding settings issue if that is the case.
