### ISSUE TITLE
Bug Fixing

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#50]
Need some bug fixing, issue are listed in the subsonic forum !
[http://forum.subsonic.org/forum/viewtopic.php?f=4&t=16372](url)

**Comment by EugeneKay** [comment]
The source for Subsonic 6.0-beta2 and after is not available. Bugfixes from those releases thus are not directly importable. Please submit an Issue or Pull Request if you have a specific problem, but these will be low-priority until after the Rebrand has completed.
