### ISSUE TITLE
Rework some themes !

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#51]
Here is a subjective list of some ugly themes of the current subsonic, we may need to rework them !
Barent Sea Theme
HD 720
HD 768
HD 1080
Ripserver
Midnight Fun
Cool and Clean
Substandard
Groove
Sonic \* ( All sonic themes )
High tech
BUUF theme

**Comment by ticklemynausea** [comment]
I actually find Groove to be one of the few bearable ones. But as you said,
subjective.

On Thu, May 5, 2016 at 1:44 PM, Jonas L. <notifications@github.com> wrote:

> Here is a subjective list of some ugly themes of the current subsonic, we
> may need to rework them !
>
> HD 720
> HD 768
> HD 1080
> Ripserver
> Midnight Fun
> Cool and Clean
> Substandard
> Groove
> Sonic * ( All sonic themes )
> High tech
> BUUF theme
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Libresonic/libresonic/issues/51>
>



-- 
Cumprimentos,
Mário Carneiro

http://mariocarneiro.info

**Comment by EugeneKay** [comment]
I have not tried any of the alternate themes, and beauty is subjective anyway. I'm not willing to begin modifying cosmetic items until after the major Rebrand tasks have been completed. Feel free to submit a Pull Request improving cosmetics, but it will not be reviewed immediately.

**Comment by alexfornuto** [comment]
I don't see this as an issue so much as an opinion piece. I suggest closing this issue, in favor of a PR with actual changes to the themes.

**Comment by jooola** [comment]
It's sure not an issue, but more like a TODO ticket !

**Comment by muff1nman** [comment]
I agree with @alexfornuto. We'll take any PRs for theme improvements but this doesn't need to be an open issue.
