### ISSUE TITLE
Release branch somehow deleted

### ISSUE THREAD

**Issue by stevenroose** [Libresonic/libresonic#56]
The release branch is the one mentioned in the install process. Yesterday there was a "release" and an "upstream" branch. Currenty both disappeared and only a "develop" branch remains..

**Comment by stevenroose** [comment]
Hmm, [I see](https://github.com/Libresonic/libresonic/issues/41#issuecomment-217688740).

I think I better wait until install flow is worked out for the new history before installing :) Great work you are doing btw!

**Comment by EugeneKay** [comment]
I will update the documentation to match.
