### ISSUE TITLE
Add Let's Encrypt support

### ISSUE THREAD

**Issue by IwishIcanFLighT** [Libresonic/libresonic#58]
Hi there,

I'm not gonna beat around the bush here: [privacy matters](https://blog.mozilla.org/blog/2016/02/16/help-us-spread-the-word-encryption-matters/).

After a long beta, [Let's Encrypt](https://letsencrypt.org/) was recently released but the current implementation of SSL in Subsonic doesn't make things easy.
[I've made myself a quick script to "facilitate" the process](http://forum.subsonic.org/forum/viewtopic.php?f=6&t=9400&p=70255#p70975), but there's definitely room for improvements imho.

Adding a seamless SSL implementation to Subsonic would encourage people to use SSL more frequently.

**Comment by EugeneKay** [comment]
I completely agree: TLS/SSL is important, and should be used everywhere.

However, I do not believe that there is any point in implementing ACME(the Let's Encrypt protocol) at this time. Libresonic is primarily packaged as a WAR to be run inside of an application server(eg, Apache Tomcat), and does not directly speak HTTP by itself. The subsonic-booter application is used for the RPM/Deb/Exe targets and includes HTTP/S support, but I am not presently building against those targets and do not have any plans to do so.

I will leave this Issue open to solicit patches.

**Comment by stevenroose** [comment]
I think the better option for supporting TLS is by using a reverse proxy like nginx.

**Comment by jooola** [comment]
Could we think about Haproxy too ? i'm using it and don't get this working ...

**Comment by IwishIcanFLighT** [comment]
My current setup already uses a reverse proxy with Apache.

The issue I'm facing is that Apache needs to bind a HTTPS virtual host to a HTTPS listening host.

Binding a reverse proxy for a HTTPS VH to a HTTP host such as LibreSonic on `http://0.0.0.0:4040` results to a handshake error.
Same goes for using a self-generated certificate on LibreSonic side.

Beside, I don't think having a non SSL host listening behind a SSL reverse proxy is a great idea in terms of security, but don't quote me on that.

In order to make it work properly with a behind proxy, you have to convert the certificate to LibreSonic's format so that both LibreSonic and Reverse Proxy use the "same" certificate.

That being said, I completely understand that it's not a priority at this point in time for LibreSonic, I just want to point that out for future releases. :wink:

**Comment by csobsidian** [comment]
I'm positive that there is a way to get Apache to proxy your HTTPS into HTTP. There are many places that do this on their backend to reduce the server load from the encryption.

**Comment by joshuaboniface** [comment]
@jooola I encountered this as well: weird blank screens when behind HAProxy in SSL mode?

The solution for me ended up being: let HAProxy connect to Subsonic's default SSL, but with cert checking disabled:

```
backend back_sub-http
        mode http
        server subsoni        1.1.1.1:8443 check ssl verify none
```

This lets you put a legit cert (e.g. LE, which I too am using) in front of Subsonic without hassling with insecure elements.

**Comment by jooola** [comment]
@joshuaboniface ! Damn thanks a lot ! 
Why don't we just put all the subsonic links in HTTPS instand of changing them when we enable ssl in subsonic ?

**Comment by fuzzynectarine** [comment]
Would this be an appropriate direction for supporting base64 ssl certificates in the libresonic-booter script? Or is it too much of a hack?
#129

**Comment by stevenroose** [comment]
I agree with @EugeneKay that TLS/SSL is outside the scope of this project and should be handled by a reverse proxy.

**Comment by jt112** [comment]
I concur with @IwishIcanFLighT that encryption is essential.  Passing this responsibility off to users by asking them to learn and implement reserve proxy is, in my opinion, shirking responsibility for basic functionality that should be present in any network service.

**Comment by EugeneKay** [comment]
@jt112 Libresonic is packaged as a WAR to be run under an application server, eg Tomcat. I do not like the standalone packages and they are probably going to be removed in the future.

**Comment by muff1nman** [comment]
I think we should reconsider this. Standalone applications are becoming more prevalent than depending on tomcat. @biconou I think is very much so interested in getting spring boot working which would make this more manageable. In addition, I think its important that we help users in securing their application, and telling them to setup their own reverse proxy is going against that.

**Comment by joshuaboniface** [comment]
I have to agree with @EugeneKay here. SSL is outside of the scope of Librrsonic, and I personally hated the hacks I needed to do to get the stock Subsonic packages (with the booster) to work with an SSL-stripping-and-enforcing reverse-proxy. Tomcat and reverse proxies are trivial to set up if you want SSL support.
