### ISSUE TITLE
Reset Password System

### ISSUE THREAD

**Issue by jooola** [Libresonic/libresonic#60]
The reset password system is currently using a subsonic smtp server. We could add some settings to configure our own smtp server to send forgotten passwords !

Edit : Sorry @bajansen thats what i meant ( set up a configurable smtp server for each one )

**Comment by bajansen** [comment]
The password reset system currently connects to the subsonic backend (hosted by Sindre) which then sends an e-mail with a new password to the user's e-mail address. I think it would be preferable to rewrite the reset password mechanism to actually use a configurable SMTP server and not depend on a central libresonic server.

**Comment by alexfornuto** [comment]
I know this is only tangendental to your point, but I think the biggest password-related issue, at least since the last time I looked, was that passwords are stored insecurely, with no encryption.

**Comment by EugeneKay** [comment]
Resolved by #87
