### ISSUE TITLE
Set up a Community space

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#63]
A Community space to discuss Libresonic is needed. This space will have "chatter" directed to it that otherwise leaks into Github's Issues system.

**Comment by EugeneKay** [comment]
I have registered the #libresonic channel on the [Freenode](http://freenode.net/) IRC network.

I do not have any desire to moderate a forum, mailing-list, or other venue. Input welcomed for a low-effort system(preferably free or freely-hosted) that is spam-resistant, possibly Github-integrated?

**Comment by csobsidian** [comment]
Not many good options for low-maintenance, free and hosted solutions.

ProBoards has free hosting for forums with unlimited users/posts. $14/yr and it can be in the libresonic.org domain.

Libresonic sub-reddit?

**Comment by nathan-sain** [comment]
[Gitter](https://gitter.im) is a nice chat / discussion platform that integrates with Github and it's free if you don't need more than 25 users at a time.

**Comment by EugeneKay** [comment]
I have created a [subreddit](https://www.reddit.com/r/libresonic/), we'll see how that fares for now.

**Comment by jooola** [comment]
Why not phpbb ?
[https://www.phpbb.com/](url)

**Comment by EugeneKay** [comment]
I already maintain [agile-php](https://github.com/eugenekay/agile-php), and do not want to deal with a self-hosted application. Reddit+IRC should suffice for now; we'll re-examine if this is untenable.
