### ISSUE TITLE
Document installation and setup

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#64]
We need documentation for installation, setup, and basic usage of a new server. INSTALL covers only the build steps right now. Major points to cover:
- Set up a WAR container(eg, Tomcat)
- Create the necessary data directories(eg, /var/subsonic)
- Install the Libresonic WAR
- Transcoder setup?
- User creation/management
- Library management
- Reverse-proxy setup, SSL

Documentation should be in Markdown, stored under a documentation/ folder. Screenshots would be great, but should wait until after #40 is complete or they will need to be re-done.

**Comment by alexfornuto** [comment]
I can help. I've written similar [before](https://www.linode.com/docs/applications/media-servers/subsonic)

**Comment by jooola** [comment]
Can't we make the whole installer package ? for Linux, Windows, Standalone,....
It would be more user friendly for the beginners !
So may need to build a doc for each system !

**Comment by EugeneKay** [comment]
I have created #65 concerning building other targets.

That style looks perfect. We will want to address the most "common" OSes: RedHat-alike, Debian-alike, Windows, and OS X.

**Comment by croquagei** [comment]
I've never written documentation before and have no idea where to start in markdown.  

But I'm more than happy to document the process for installing and deploying the War in FreeBSD if someone can either guide me through using markdown

**Comment by csobsidian** [comment]
Check out this Github markdown [cheat sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) to get a good start. There are good links on that page for further information.

**Comment by alexfornuto** [comment]
https://github.com/Libresonic/libresonic/pull/96
