### ISSUE TITLE
Set up a build server

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#67]
@zifnab06 has volunteered to run an automated build server(Jenkins). I leave the implementation details to him.

**Comment by zifnab06** [comment]
Test

**Comment by zifnab06** [comment]
https://jenkins.zifnab.net/job/libresonic/

Builds daily, along with manual-triggered builds. Probable features, for later: only build when changes have happened, *maybe* build PRs if I can do so without exposing private data on server.

**Comment by alexfornuto** [comment]
@EugeneKay Can these builds be considered stable, and used in documentation for easy installation?

**Comment by zifnab06** [comment]
I'm just going through my unread github stuff....

These builds should not be considered stable. They're built from the current develop branch as changes are pushed. The latest stable build can be found here: https://github.com/Libresonic/libresonic/releases
