### ISSUE TITLE
Keep Compatibilitty with android and ios app

### ISSUE THREAD

**Issue by djdmd** [Libresonic/libresonic#70]
Hello
I have my childs using android and ios app to keep their music synchronised . so please , if possible can you keep compatibility with these apps.

Thanks

**Comment by EugeneKay** [comment]
Part of #40 is to contact maintainers of popular Subsonic clients to ensure that compatibility is maintained. Additionally, we especially mention "No Breakage" in [CONTRIBUTING](https://github.com/Libresonic/libresonic/blob/develop/CONTRIBUTING.md). So rest assured - the API won't suddenly break.
