### ISSUE TITLE
Corrupt zip files

### ISSUE THREAD

**Issue by davidkeefe24** [Libresonic/libresonic#72]
When using the "Download all" link you get a corrupt zip file. Selecting all files and using the dropdown option to download works fine though.

**Comment by chpio** [comment]
git works too...

**Comment by davidkeefe24** [comment]
I mean in the web interface, not trying to download front the repo...

**Comment by EugeneKay** [comment]
What link/URL are you attempting to use? [Download All](https://github.com/Libresonic/libresonic/archive/develop.zip) on the [front page of this repo](https://github.com/Libresonic/libresonic) gives a valid ZIP archive for me.

In any case, this would be a problem for Github Support.

**Comment by davidkeefe24** [comment]
I am not talking about anything to do with GitHub. I have built the app and installed without problem, but I am unable to use the download feature properly. 

When viewing an album, the "Download all" link at the top of the page results in a corrupt zip file download. As I explained above, you can avoid this and get a proper zip download by selecting all files and using the download option from the "Selected songs..." dropdown menu.

**Comment by csobsidian** [comment]
I have been unable to replicate this issue with the current development branch. Zip archives made from the "Download All" link work for me in both Ubuntu 16.04 and Win7.

**Comment by davidkeefe24** [comment]
I have just tried to download several albums, all of which gave me a corrupt zip.

Others are reporting the issue too on reddit https://www.reddit.com/r/subsonic/comments/3ykqzl/corrupt_zip_archives_when_downloading/

**Comment by EugeneKay** [comment]
I am also unable to reproduce this issue in develop or stable. Without reproduction, there's basically nothing we can do. Please provide more detail, including but not limited to:

- Libresonic build being used(from Github Releases, not self-built)
- OS/Version/Architecture of server
- Versions of Tomcat, Java
- Link to Albums causing issue(libre media only, please)
- Perform on a clean Libresonic install?
- Any transcoding, download, or other settings changed from the defaultss
- A login to the server(email me or contact in IRC)
- libresonic.log & catalina.out

Thank you.

**Comment by davidkeefe24** [comment]
Turned out to be an issue with my OSX Archive Utility.

Not sure why the 2 methods would yield different results, but the zup file extracted fine with another app.
