### ISSUE TITLE
Missing 5.3 release / Breaks existing docker setups

### ISSUE THREAD

**Issue by makkus** [Libresonic/libresonic#73]
Hiya,

because of the recent re-org of the repos, this file is not accessible anymore:

https://github.com/EugeneKay/subsonic/releases/download/v5.3-kang/subsonic-v5.3-kang.war"

Any chance somebody could upload it somewhere so I can get the docker container I just deleted running again?

Thanks!

**Comment by EugeneKay** [comment]
The old 'kang' builds were removed automatically by Github when the old history/tags were deleted. I was not aware that anybody was referencing them directly by URL, and they should not have done so.

I do not have the exact WAR that you're looking for, but I can share [libresonic-5.3-develop.war](https://libresonic.org/release/libresonic-5.3-develop.war), which is based upon develop branch and what my personal instance is running. Do not put this into any long-term scripts; it WILL be deleted when an official 6.0 Libresonic release is made.

I am leaving this Issue open as a TODO: provide long-term-stable download paths.

**Comment by EugeneKay** [comment]
Users should download Libresonic from [Github](https://github.com/Libresonic/libresonic/releases). Packagers can reference the [release repository](https://libresonic.org/release/), but the URLs there are not guaranteed to be stable. Please do not hardcode these URLs or place undue load upon the Libresonic webserver. Leaving this issue open as a reminder to create DOWNLOAD or USAGE document for the long-term.

**Comment by makkus** [comment]
Thanks. I guess the change to Libresonic was a bit of a special circumstance, otherwise I would have thought referencing a release on github is a good idea, since those usually stay up and don't change (being releases). Plus, Github should be able to handle the load (I wouldn't put anything like that on my own webserver if there is such a good alternative for hosting the releases. People will use that for automated downloads, for example in Docker. I guarantee it :-) ). So, if I were you I'd use Github for downloads. In addition, you could automate the build process.

Either way, thanks for the war. Using this manually in my docker build dir for now, until there is a first 'proper' release.

**Comment by EugeneKay** [comment]
There isn't any good way to maintain compatibility when moving to an orphan branch, so I didn't bother(as you noticed). 

Github will likely be the "go-to" for releases, with https://libresonic.org/release provided as a a Mirror. I've asked @zifnab06 to look into automatically pushing releases to Github. Once that is setup I'll write a USAGE document to make this official.

**Comment by chpio** [comment]
you also could upload it to [ipfs](https://ipfs.io). ipfs is immutable, so a released release would stay as long as there is someone hosting it on the network.
