### ISSUE TITLE
SNI support for HTTPS URLs

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#74]
The version of httpclient being shipped with Libresonic does not support SNI with HTTPS URLs, eg for version updates. Reference #44, but it is used in a lot of other places. Should httpclient be upgraded(refactoring needed) or replaced with something else?

**Comment by bfkelsey** [comment]
Might be able to use something like http://square.github.io/retrofit/ for this. I could start working on it if that works.

**Comment by jooola** [comment]
This can be closed right ? since #167  Fix this.
