### ISSUE TITLE
Migrate Subsonic settings/database

### ISSUE THREAD

**Issue by EugeneKay** [Libresonic/libresonic#75]
We need to scan for and migrate/import Subsonic settings & database for new installs. The manual process is:

```
$ cd /var/
$ mkdir libresonic
$ chown tomcat:tomcat libresonic/
$ cp subsonic/subsonic.properties subsonic/db libresonic/ -R
$ rename subsonic libresonic libresonic/* libresonic/db/*
$ sed -i 's/subsonic/libresonic/g' libresonic/libresonic.properties
```

**Comment by fxthomas** [comment]
Just leaving that here, but if people (like me) installed the Subsonic beta versions before migrating to Libresonic, they should probably use the following SQL to undo the schema migration :

```sql
delete from version where version = 26;
drop table video_conversion;
delete from user_role where role_id = 12;
delete from role where id = 12;
```

**Comment by muff1nman** [comment]
I do not think we should automate this. It would be fragile and hard to do correctly.

**Comment by muff1nman** [comment]
Documentation should suffice.

**Comment by jooola** [comment]
We can close right ? Documentations has been build ?!
