### ISSUE TITLE
Migrate to Spring 4.2.6

### ISSUE THREAD

**Issue by muff1nman** [Libresonic/libresonic#80]
Libresonic is currently on some ancient 2.X version of Spring. According to this [doc](https://github.com/spring-projects/spring-framework/wiki/migrating-from-earlier-versions-of-the-spring-framework), 2.X isn't supported anymore.

I think this upgrade is needed for a couple reasons:
- Better support for integration testing
- Few developers use/know how to work with spring 2.X
- Spring 3 and 4 have a bunch of cool features that would be helpful for streamlining/cleaning up the codebase
- Addresses possible bugs/security issues

I have already started working on this and these are the problems I've run into so far:
- [X] Pom: Update spring version to 3.X.X as an intermediate
- [x] Pom: Update spring version to 4.2.6.RELEASE
- [X] Pom: Remove spring artifact and replace it with spring-webmvc
- [x] Controller: Migrate Controllers extending SimpleFormController to annotations
- [x] Controller: Update spring bean controller definitions (would like to use component-scan, but that's another effort I'm afraid
- [x] Controller: Remove url mapping in xml 
- [x] DB: Migrate queryForInt and friends to queryForObject
- [X] DB: Change usages of ParameterizedRowMapper to just RowMapper
- [ ] Other Unexpected Surprises
  - [x]  org.acegisecurity is not compatible with spring3. Rip it out and replace it with spring security.
    - [ ]  Update LDAP support to use spring security
    - [x]  Migrate to spring security remember me
    - [x] Fix login failure message

Spring 4 work is at: https://github.com/muff1nman/libresonic/tree/spring-4-update
Spring 3 work is at: https://github.com/muff1nman/libresonic/tree/spring-3-update

**Comment by makkus** [comment]
Good idea. I'd wager this will be a fairly big change (it'd probably be also good to go through the codebase and look out for stuff that could be replaced by new spring features that didn't exist in Spring 2.X), but it'd be a great base to build further features upon.

**Comment by EugeneKay** [comment]
Wow! This is an ambitious undertaking. I agree that  there are a lot of very old dependencies that should be updated, including Spring. I don't think this should negatively affect anything, but we'll need to test this a bunch before merging. I'm going to put this on the Future milestone for now; we'll need to test extensively before merging. It sounds like you know what you're doing; go for it!

I don't know what sort of scope / timetable this will take. Give me a shout if this needs a feature branch and I'll grant you some org-level permissions.

**Comment by muff1nman** [comment]
Even though the goal is to get to spring 4, I've created a branch specifically for spring 3 as it might be a good milestone. Links are in the issue description.

**Comment by chetan** [comment]
@muff1nman your TODO list above doesn't match what's in your branch currently. Do you have some commits you haven't pushed yet? I'd love to help out here but don't want to duplicate any work.

**Comment by chetan** [comment]
pushed some more here

https://github.com/chetan/libresonic/tree/spring-4-update

**Comment by muff1nman** [comment]
Ah good catch, I haven't done all of them in my spring-4-update branch.

My intent is to get spring-3-update merged first as spring 3 mainly deprecates things, while spring 4 has removed them entirely.

**Comment by muff1nman** [comment]
@chetan and sure any help is appreciated. Either submit pull requests to one of my branches or to this project directly.

**Comment by biconou** [comment]
I agree that a Spring upgrade is necessary.

**Comment by muff1nman** [comment]
Been a bit busy with other stuff, but am still working slowly on this. Most recently found org.acegisecurity is not compatible with spring3.

**Comment by biconou** [comment]
I think the equivalent is now Spring Security.
https://en.wikipedia.org/wiki/Spring_Security

**Comment by muff1nman** [comment]
@biconou correct. Actually spring security was born from acegisecurity which I am grateful for as its been pretty straightforward to upgrade it.

**Comment by muff1nman** [comment]
Thanks @biconou for taking on much of this work! Although we may need to revisit the ldap authentication, that should be its own ticket at this point.
