### ISSUE TITLE
Problem while building debian version

### ISSUE THREAD

**Issue by djdmd** [Libresonic/libresonic#90]
Hello 
i've tried the install doc and when i type this 
` mvn -P full -pl subsonic-booter -am install`

i have this message 
`[INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/net/sourceforge/subsonic/subsonic/6.0.1/subs                                                                                                       onic-6.0.1.pom
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-booter:6.0.1 (/home/pi/libresonic/subs                                                                                                       onic-booter/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact net.sourceforge.subsonic:subson                                                                                                       ic:pom:6.0.1 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' point                                                                                                       s at wrong local POM @ line 9, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-windows:6.0.1 (/home/pi/libr                                                                                                       esonic/subsonic-installer-windows/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-mac:6.0.1 (/home/pi/libreson                                                                                                       ic/subsonic-installer-mac/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-debian:6.0.1 (/home/pi/libre                                                                                                       sonic/subsonic-installer-debian/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-rpm:6.0.1 (/home/pi/libreson                                                                                                       ic/subsonic-installer-rpm/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-assembly:6.0.1 (/home/pi/libresonic/su                                                                                                       bsonic-assembly/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the followin                                                                                                       g articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
root@raspberrypi3:/home/pi/libresonic# mvn -P full -pl libresonic-booter -am install
[INFO] Scanning for projects...
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-booter:6.0.1 (/home/pi/libresonic/subs                                                                                                       onic-booter/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 9, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-windows:6.0.1 (/home/pi/libr                                                                                                       esonic/subsonic-installer-windows/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-mac:6.0.1 (/home/pi/libreson                                                                                                       ic/subsonic-installer-mac/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-debian:6.0.1 (/home/pi/libre                                                                                                       sonic/subsonic-installer-debian/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-installer-rpm:6.0.1 (/home/pi/libreson                                                                                                       ic/subsonic-installer-rpm/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-assembly:6.0.1 (/home/pi/libresonic/su                                                                                                       bsonic-assembly/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find net.sourceforge.subsonic:subsonic:pom:6                                                                                                       .0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution wi                                                                                                       ll not be reattempted until the update interval of central has elapsed or updates are forced a                                                                                                       nd 'parent.relativePath' points at wrong local POM @ line 10, column 13 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the followin                                                                                                       g articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
root@raspberrypi3:/home/pi/libresonic# [INFO] Scanning for projects...
Downloading: https://repo.maven.apache.org/maven2/net/sourceforge/subsonic/subsonic/6.0.1/subs                                                                                                       onic-6.0.1.pom
[ERROR] The build could not read 6 projects -> [Help 1]
[ERROR]
[ERROR]   The project net.sourceforge.subsonic:subsonic-booter:6.0.1 (/home/pi/libresonic/subs                                                                                                       onic-booter/pom.xml) has 1 error
[ERROR]     Non-resolvablebash: [INFO] : commande introuvable
root@raspberrypi3:/home/pi/libresonic# Downloading: https://repo.maven.apache.org/maven2/net/sourceforge/subsonic/subsonic                                                                           /6.0.1/subs                            onic-6.0.1.pom
`
thx for help

**Comment by bajansen** [comment]
The 'stable' branch is currently not exactly as stable as it should be. Building the develop branch however should work for now. Note that you should replace every occurrence of 'subsonic' in the installation instructions with 'libresonic' to build the develop branch.

**Comment by EugeneKay** [comment]
I have updated the INSTALL instructions in debd7aa to address this common confusion.

**Comment by djdmd** [comment]
Nice i try with develop branch 
 git clone -b develop git://github.com/Libresonic/libresonic.git

Build Ok , install ok , i am scanning library .

nginx vhost is the same as for subsonic .

Thsx for answering my question.
