### ISSUE TITLE
[SOLVED]"Transcoders does not appear to be installed." - how to install?

### ISSUE THREAD

**Issue by D3add3d** [Libresonic/libresonic#98]
So after deploying the v6.1.beta1 WAR from releases and creating libresonic directory in /var I changed the admin password and noticed a red text stating that transcoders are not installed, since I could not find anything about these transcoders I would like to ask how does one install them and from where.

**Comment by bajansen** [comment]
If your libresonic directory is /var/libresonic, transcoders should be installed in /var/libresonic/transcode. The easiest way to do this is by installing ffmpeg and then executing `ln -s $(which ffmpeg) /var/libresonic/transcode/`. This should make libresonic work with the default transcoding settings.

**Comment by D3add3d** [comment]
Thank you @bajansen ! I did not think it was as simple as creating a symlink to ffmpeg :open_mouth:

**Comment by alexfornuto** [comment]
Does this need to be done with each fresh install? If so, I'll add it to the install guide I'm working on.

**Comment by D3add3d** [comment]
@alexfornuto it does appear to be the case
